LogConfig: true
Logger:
  AppName: helpdesk
  Build: dev
  Level: debug
ConfigReader:
  Name: ""
  Format: ""
  Consul:
    Address: ""
    Token: ""
    Path: ""
  Zookeeper:
    Address: ""
    Path: ""
    Username: ""
    Password: ""
AppNames:
- HTTP_SERVER
- GRPC_SERVER
Server:
  GRPCPort: 8097
  HTTPPort: 8098
Repository:
  Name: postgres   # postgres/memory
  Postgres:
    Host: 192.168.1.100
    Port: 5432
    Username: admin
    Password: OSwfiTlc1r5W7Z
    DBName: helpdesk
    SSLMode: disable
    MaxOpenConns: 20
    MaxIdleConns: 10
    ConnMaxLifetime: 30m
    ConnMaxIdleTime: 5m
Service:
  RatingEntities: ["app", "topic", "question"]
  IssueEntities: ["app", "topic", "question"]
  IssueTypes: ["issue", "improvement", "other"]
  AllowedProductIds: [101, 102, 103, 104, 105]
  MaxRating: 5
Debug:
  Enabled: true
  EnablePprof: true