services:
  helpdesk:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: helpdesk
    ports:
      - "8097:8097" # HTTP Server
      - "8098:8098" # gRPC Server
    restart: always
