// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: proto/helpdesk/v1/admin.proto

package helpdesk_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Product represents a product/service offering
type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	IsActive      bool                   `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_proto_helpdesk_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helpdesk_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_proto_helpdesk_v1_admin_proto_rawDescGZIP(), []int{0}
}

func (x *Product) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Product) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Product) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// ProductEntity represents an entity type within a product (e.g., "app", "topic")
type ProductEntity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId     int64                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	EntityName    string                 `protobuf:"bytes,3,opt,name=entity_name,json=entityName,proto3" json:"entity_name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductEntity) Reset() {
	*x = ProductEntity{}
	mi := &file_proto_helpdesk_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductEntity) ProtoMessage() {}

func (x *ProductEntity) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helpdesk_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductEntity.ProtoReflect.Descriptor instead.
func (*ProductEntity) Descriptor() ([]byte, []int) {
	return file_proto_helpdesk_v1_admin_proto_rawDescGZIP(), []int{1}
}

func (x *ProductEntity) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductEntity) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ProductEntity) GetEntityName() string {
	if x != nil {
		return x.EntityName
	}
	return ""
}

func (x *ProductEntity) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProductEntity) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// ProductIssueType represents an issue type within a product
type ProductIssueType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId     int64                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	TypeName      string                 `protobuf:"bytes,3,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductIssueType) Reset() {
	*x = ProductIssueType{}
	mi := &file_proto_helpdesk_v1_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductIssueType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductIssueType) ProtoMessage() {}

func (x *ProductIssueType) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helpdesk_v1_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductIssueType.ProtoReflect.Descriptor instead.
func (*ProductIssueType) Descriptor() ([]byte, []int) {
	return file_proto_helpdesk_v1_admin_proto_rawDescGZIP(), []int{2}
}

func (x *ProductIssueType) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductIssueType) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ProductIssueType) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

func (x *ProductIssueType) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProductIssueType) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type GetProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductRequest) Reset() {
	*x = GetProductRequest{}
	mi := &file_proto_helpdesk_v1_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRequest) ProtoMessage() {}

func (x *GetProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helpdesk_v1_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRequest.ProtoReflect.Descriptor instead.
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_helpdesk_v1_admin_proto_rawDescGZIP(), []int{3}
}

func (x *GetProductRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductResponse) Reset() {
	*x = GetProductResponse{}
	mi := &file_proto_helpdesk_v1_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductResponse) ProtoMessage() {}

func (x *GetProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helpdesk_v1_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductResponse.ProtoReflect.Descriptor instead.
func (*GetProductResponse) Descriptor() ([]byte, []int) {
	return file_proto_helpdesk_v1_admin_proto_rawDescGZIP(), []int{4}
}

func (x *GetProductResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type ListProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsRequest) Reset() {
	*x = ListProductsRequest{}
	mi := &file_proto_helpdesk_v1_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsRequest) ProtoMessage() {}

func (x *ListProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helpdesk_v1_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsRequest.ProtoReflect.Descriptor instead.
func (*ListProductsRequest) Descriptor() ([]byte, []int) {
	return file_proto_helpdesk_v1_admin_proto_rawDescGZIP(), []int{5}
}

func (x *ListProductsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListProductsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsResponse) Reset() {
	*x = ListProductsResponse{}
	mi := &file_proto_helpdesk_v1_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsResponse) ProtoMessage() {}

func (x *ListProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helpdesk_v1_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsResponse.ProtoReflect.Descriptor instead.
func (*ListProductsResponse) Descriptor() ([]byte, []int) {
	return file_proto_helpdesk_v1_admin_proto_rawDescGZIP(), []int{6}
}

func (x *ListProductsResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *ListProductsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CreateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	IsActive      bool                   `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductRequest) Reset() {
	*x = CreateProductRequest{}
	mi := &file_proto_helpdesk_v1_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductRequest) ProtoMessage() {}

func (x *CreateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helpdesk_v1_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductRequest.ProtoReflect.Descriptor instead.
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_helpdesk_v1_admin_proto_rawDescGZIP(), []int{7}
}

func (x *CreateProductRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateProductRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type CreateProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductResponse) Reset() {
	*x = CreateProductResponse{}
	mi := &file_proto_helpdesk_v1_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductResponse) ProtoMessage() {}

func (x *CreateProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helpdesk_v1_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductResponse.ProtoReflect.Descriptor instead.
func (*CreateProductResponse) Descriptor() ([]byte, []int) {
	return file_proto_helpdesk_v1_admin_proto_rawDescGZIP(), []int{8}
}

func (x *CreateProductResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type UpdateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	IsActive      bool                   `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductRequest) Reset() {
	*x = UpdateProductRequest{}
	mi := &file_proto_helpdesk_v1_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductRequest) ProtoMessage() {}

func (x *UpdateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helpdesk_v1_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_helpdesk_v1_admin_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateProductRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateProductRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type UpdateProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductResponse) Reset() {
	*x = UpdateProductResponse{}
	mi := &file_proto_helpdesk_v1_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductResponse) ProtoMessage() {}

func (x *UpdateProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helpdesk_v1_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductResponse.ProtoReflect.Descriptor instead.
func (*UpdateProductResponse) Descriptor() ([]byte, []int) {
	return file_proto_helpdesk_v1_admin_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateProductResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type DeleteProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductRequest) Reset() {
	*x = DeleteProductRequest{}
	mi := &file_proto_helpdesk_v1_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductRequest) ProtoMessage() {}

func (x *DeleteProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helpdesk_v1_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductRequest.ProtoReflect.Descriptor instead.
func (*DeleteProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_helpdesk_v1_admin_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteProductRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductResponse) Reset() {
	*x = DeleteProductResponse{}
	mi := &file_proto_helpdesk_v1_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductResponse) ProtoMessage() {}

func (x *DeleteProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helpdesk_v1_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductResponse.ProtoReflect.Descriptor instead.
func (*DeleteProductResponse) Descriptor() ([]byte, []int) {
	return file_proto_helpdesk_v1_admin_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteProductResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListProductEntitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductEntitiesRequest) Reset() {
	*x = ListProductEntitiesRequest{}
	mi := &file_proto_helpdesk_v1_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductEntitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductEntitiesRequest) ProtoMessage() {}

func (x *ListProductEntitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helpdesk_v1_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductEntitiesRequest.ProtoReflect.Descriptor instead.
func (*ListProductEntitiesRequest) Descriptor() ([]byte, []int) {
	return file_proto_helpdesk_v1_admin_proto_rawDescGZIP(), []int{13}
}

func (x *ListProductEntitiesRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ListProductEntitiesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListProductEntitiesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListProductEntitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entities      []*ProductEntity       `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductEntitiesResponse) Reset() {
	*x = ListProductEntitiesResponse{}
	mi := &file_proto_helpdesk_v1_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductEntitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductEntitiesResponse) ProtoMessage() {}

func (x *ListProductEntitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helpdesk_v1_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductEntitiesResponse.ProtoReflect.Descriptor instead.
func (*ListProductEntitiesResponse) Descriptor() ([]byte, []int) {
	return file_proto_helpdesk_v1_admin_proto_rawDescGZIP(), []int{14}
}

func (x *ListProductEntitiesResponse) GetEntities() []*ProductEntity {
	if x != nil {
		return x.Entities
	}
	return nil
}

type CreateProductEntityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	EntityName    string                 `protobuf:"bytes,2,opt,name=entity_name,json=entityName,proto3" json:"entity_name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductEntityRequest) Reset() {
	*x = CreateProductEntityRequest{}
	mi := &file_proto_helpdesk_v1_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductEntityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductEntityRequest) ProtoMessage() {}

func (x *CreateProductEntityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helpdesk_v1_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductEntityRequest.ProtoReflect.Descriptor instead.
func (*CreateProductEntityRequest) Descriptor() ([]byte, []int) {
	return file_proto_helpdesk_v1_admin_proto_rawDescGZIP(), []int{15}
}

func (x *CreateProductEntityRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CreateProductEntityRequest) GetEntityName() string {
	if x != nil {
		return x.EntityName
	}
	return ""
}

func (x *CreateProductEntityRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateProductEntityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entity        *ProductEntity         `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductEntityResponse) Reset() {
	*x = CreateProductEntityResponse{}
	mi := &file_proto_helpdesk_v1_admin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductEntityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductEntityResponse) ProtoMessage() {}

func (x *CreateProductEntityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helpdesk_v1_admin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductEntityResponse.ProtoReflect.Descriptor instead.
func (*CreateProductEntityResponse) Descriptor() ([]byte, []int) {
	return file_proto_helpdesk_v1_admin_proto_rawDescGZIP(), []int{16}
}

func (x *CreateProductEntityResponse) GetEntity() *ProductEntity {
	if x != nil {
		return x.Entity
	}
	return nil
}

type DeleteProductEntityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductEntityRequest) Reset() {
	*x = DeleteProductEntityRequest{}
	mi := &file_proto_helpdesk_v1_admin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductEntityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductEntityRequest) ProtoMessage() {}

func (x *DeleteProductEntityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helpdesk_v1_admin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductEntityRequest.ProtoReflect.Descriptor instead.
func (*DeleteProductEntityRequest) Descriptor() ([]byte, []int) {
	return file_proto_helpdesk_v1_admin_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteProductEntityRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteProductEntityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductEntityResponse) Reset() {
	*x = DeleteProductEntityResponse{}
	mi := &file_proto_helpdesk_v1_admin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductEntityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductEntityResponse) ProtoMessage() {}

func (x *DeleteProductEntityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helpdesk_v1_admin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductEntityResponse.ProtoReflect.Descriptor instead.
func (*DeleteProductEntityResponse) Descriptor() ([]byte, []int) {
	return file_proto_helpdesk_v1_admin_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteProductEntityResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListProductIssueTypesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductIssueTypesRequest) Reset() {
	*x = ListProductIssueTypesRequest{}
	mi := &file_proto_helpdesk_v1_admin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductIssueTypesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductIssueTypesRequest) ProtoMessage() {}

func (x *ListProductIssueTypesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helpdesk_v1_admin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductIssueTypesRequest.ProtoReflect.Descriptor instead.
func (*ListProductIssueTypesRequest) Descriptor() ([]byte, []int) {
	return file_proto_helpdesk_v1_admin_proto_rawDescGZIP(), []int{19}
}

func (x *ListProductIssueTypesRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ListProductIssueTypesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListProductIssueTypesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListProductIssueTypesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IssueTypes    []*ProductIssueType    `protobuf:"bytes,1,rep,name=issue_types,json=issueTypes,proto3" json:"issue_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductIssueTypesResponse) Reset() {
	*x = ListProductIssueTypesResponse{}
	mi := &file_proto_helpdesk_v1_admin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductIssueTypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductIssueTypesResponse) ProtoMessage() {}

func (x *ListProductIssueTypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helpdesk_v1_admin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductIssueTypesResponse.ProtoReflect.Descriptor instead.
func (*ListProductIssueTypesResponse) Descriptor() ([]byte, []int) {
	return file_proto_helpdesk_v1_admin_proto_rawDescGZIP(), []int{20}
}

func (x *ListProductIssueTypesResponse) GetIssueTypes() []*ProductIssueType {
	if x != nil {
		return x.IssueTypes
	}
	return nil
}

type CreateProductIssueTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	TypeName      string                 `protobuf:"bytes,2,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductIssueTypeRequest) Reset() {
	*x = CreateProductIssueTypeRequest{}
	mi := &file_proto_helpdesk_v1_admin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductIssueTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductIssueTypeRequest) ProtoMessage() {}

func (x *CreateProductIssueTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helpdesk_v1_admin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductIssueTypeRequest.ProtoReflect.Descriptor instead.
func (*CreateProductIssueTypeRequest) Descriptor() ([]byte, []int) {
	return file_proto_helpdesk_v1_admin_proto_rawDescGZIP(), []int{21}
}

func (x *CreateProductIssueTypeRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CreateProductIssueTypeRequest) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

func (x *CreateProductIssueTypeRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateProductIssueTypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IssueType     *ProductIssueType      `protobuf:"bytes,1,opt,name=issue_type,json=issueType,proto3" json:"issue_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductIssueTypeResponse) Reset() {
	*x = CreateProductIssueTypeResponse{}
	mi := &file_proto_helpdesk_v1_admin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductIssueTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductIssueTypeResponse) ProtoMessage() {}

func (x *CreateProductIssueTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helpdesk_v1_admin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductIssueTypeResponse.ProtoReflect.Descriptor instead.
func (*CreateProductIssueTypeResponse) Descriptor() ([]byte, []int) {
	return file_proto_helpdesk_v1_admin_proto_rawDescGZIP(), []int{22}
}

func (x *CreateProductIssueTypeResponse) GetIssueType() *ProductIssueType {
	if x != nil {
		return x.IssueType
	}
	return nil
}

type DeleteProductIssueTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductIssueTypeRequest) Reset() {
	*x = DeleteProductIssueTypeRequest{}
	mi := &file_proto_helpdesk_v1_admin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductIssueTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductIssueTypeRequest) ProtoMessage() {}

func (x *DeleteProductIssueTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helpdesk_v1_admin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductIssueTypeRequest.ProtoReflect.Descriptor instead.
func (*DeleteProductIssueTypeRequest) Descriptor() ([]byte, []int) {
	return file_proto_helpdesk_v1_admin_proto_rawDescGZIP(), []int{23}
}

func (x *DeleteProductIssueTypeRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteProductIssueTypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductIssueTypeResponse) Reset() {
	*x = DeleteProductIssueTypeResponse{}
	mi := &file_proto_helpdesk_v1_admin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductIssueTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductIssueTypeResponse) ProtoMessage() {}

func (x *DeleteProductIssueTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helpdesk_v1_admin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductIssueTypeResponse.ProtoReflect.Descriptor instead.
func (*DeleteProductIssueTypeResponse) Descriptor() ([]byte, []int) {
	return file_proto_helpdesk_v1_admin_proto_rawDescGZIP(), []int{24}
}

func (x *DeleteProductIssueTypeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_helpdesk_v1_admin_proto protoreflect.FileDescriptor

const file_proto_helpdesk_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/helpdesk/v1/admin.proto\x12\x02v1\"\xaa\x01\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tis_active\x18\x04 \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\x03R\tupdatedAt\"\xa0\x01\n" +
	"\rProductEntity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x03R\tproductId\x12\x1f\n" +
	"\ventity_name\x18\x03 \x01(\tR\n" +
	"entityName\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\"\x9f\x01\n" +
	"\x10ProductIssueType\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x03R\tproductId\x12\x1b\n" +
	"\ttype_name\x18\x03 \x01(\tR\btypeName\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\"#\n" +
	"\x11GetProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\";\n" +
	"\x12GetProductResponse\x12%\n" +
	"\aproduct\x18\x01 \x01(\v2\v.v1.ProductR\aproduct\"F\n" +
	"\x13ListProductsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"U\n" +
	"\x14ListProductsResponse\x12'\n" +
	"\bproducts\x18\x01 \x03(\v2\v.v1.ProductR\bproducts\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"y\n" +
	"\x14CreateProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tis_active\x18\x04 \x01(\bR\bisActive\">\n" +
	"\x15CreateProductResponse\x12%\n" +
	"\aproduct\x18\x01 \x01(\v2\v.v1.ProductR\aproduct\"y\n" +
	"\x14UpdateProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tis_active\x18\x04 \x01(\bR\bisActive\">\n" +
	"\x15UpdateProductResponse\x12%\n" +
	"\aproduct\x18\x01 \x01(\v2\v.v1.ProductR\aproduct\"&\n" +
	"\x14DeleteProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"1\n" +
	"\x15DeleteProductResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"l\n" +
	"\x1aListProductEntitiesRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"L\n" +
	"\x1bListProductEntitiesResponse\x12-\n" +
	"\bentities\x18\x01 \x03(\v2\x11.v1.ProductEntityR\bentities\"~\n" +
	"\x1aCreateProductEntityRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x1f\n" +
	"\ventity_name\x18\x02 \x01(\tR\n" +
	"entityName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"H\n" +
	"\x1bCreateProductEntityResponse\x12)\n" +
	"\x06entity\x18\x01 \x01(\v2\x11.v1.ProductEntityR\x06entity\",\n" +
	"\x1aDeleteProductEntityRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"7\n" +
	"\x1bDeleteProductEntityResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"n\n" +
	"\x1cListProductIssueTypesRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"V\n" +
	"\x1dListProductIssueTypesResponse\x125\n" +
	"\vissue_types\x18\x01 \x03(\v2\x14.v1.ProductIssueTypeR\n" +
	"issueTypes\"}\n" +
	"\x1dCreateProductIssueTypeRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x1b\n" +
	"\ttype_name\x18\x02 \x01(\tR\btypeName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"U\n" +
	"\x1eCreateProductIssueTypeResponse\x123\n" +
	"\n" +
	"issue_type\x18\x01 \x01(\v2\x14.v1.ProductIssueTypeR\tissueType\"/\n" +
	"\x1dDeleteProductIssueTypeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\":\n" +
	"\x1eDeleteProductIssueTypeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccessB\x0fZ\r./helpdesk_v1b\x06proto3"

var (
	file_proto_helpdesk_v1_admin_proto_rawDescOnce sync.Once
	file_proto_helpdesk_v1_admin_proto_rawDescData []byte
)

func file_proto_helpdesk_v1_admin_proto_rawDescGZIP() []byte {
	file_proto_helpdesk_v1_admin_proto_rawDescOnce.Do(func() {
		file_proto_helpdesk_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_helpdesk_v1_admin_proto_rawDesc), len(file_proto_helpdesk_v1_admin_proto_rawDesc)))
	})
	return file_proto_helpdesk_v1_admin_proto_rawDescData
}

var file_proto_helpdesk_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_proto_helpdesk_v1_admin_proto_goTypes = []any{
	(*Product)(nil),                        // 0: v1.Product
	(*ProductEntity)(nil),                  // 1: v1.ProductEntity
	(*ProductIssueType)(nil),               // 2: v1.ProductIssueType
	(*GetProductRequest)(nil),              // 3: v1.GetProductRequest
	(*GetProductResponse)(nil),             // 4: v1.GetProductResponse
	(*ListProductsRequest)(nil),            // 5: v1.ListProductsRequest
	(*ListProductsResponse)(nil),           // 6: v1.ListProductsResponse
	(*CreateProductRequest)(nil),           // 7: v1.CreateProductRequest
	(*CreateProductResponse)(nil),          // 8: v1.CreateProductResponse
	(*UpdateProductRequest)(nil),           // 9: v1.UpdateProductRequest
	(*UpdateProductResponse)(nil),          // 10: v1.UpdateProductResponse
	(*DeleteProductRequest)(nil),           // 11: v1.DeleteProductRequest
	(*DeleteProductResponse)(nil),          // 12: v1.DeleteProductResponse
	(*ListProductEntitiesRequest)(nil),     // 13: v1.ListProductEntitiesRequest
	(*ListProductEntitiesResponse)(nil),    // 14: v1.ListProductEntitiesResponse
	(*CreateProductEntityRequest)(nil),     // 15: v1.CreateProductEntityRequest
	(*CreateProductEntityResponse)(nil),    // 16: v1.CreateProductEntityResponse
	(*DeleteProductEntityRequest)(nil),     // 17: v1.DeleteProductEntityRequest
	(*DeleteProductEntityResponse)(nil),    // 18: v1.DeleteProductEntityResponse
	(*ListProductIssueTypesRequest)(nil),   // 19: v1.ListProductIssueTypesRequest
	(*ListProductIssueTypesResponse)(nil),  // 20: v1.ListProductIssueTypesResponse
	(*CreateProductIssueTypeRequest)(nil),  // 21: v1.CreateProductIssueTypeRequest
	(*CreateProductIssueTypeResponse)(nil), // 22: v1.CreateProductIssueTypeResponse
	(*DeleteProductIssueTypeRequest)(nil),  // 23: v1.DeleteProductIssueTypeRequest
	(*DeleteProductIssueTypeResponse)(nil), // 24: v1.DeleteProductIssueTypeResponse
}
var file_proto_helpdesk_v1_admin_proto_depIdxs = []int32{
	0, // 0: v1.GetProductResponse.product:type_name -> v1.Product
	0, // 1: v1.ListProductsResponse.products:type_name -> v1.Product
	0, // 2: v1.CreateProductResponse.product:type_name -> v1.Product
	0, // 3: v1.UpdateProductResponse.product:type_name -> v1.Product
	1, // 4: v1.ListProductEntitiesResponse.entities:type_name -> v1.ProductEntity
	1, // 5: v1.CreateProductEntityResponse.entity:type_name -> v1.ProductEntity
	2, // 6: v1.ListProductIssueTypesResponse.issue_types:type_name -> v1.ProductIssueType
	2, // 7: v1.CreateProductIssueTypeResponse.issue_type:type_name -> v1.ProductIssueType
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_proto_helpdesk_v1_admin_proto_init() }
func file_proto_helpdesk_v1_admin_proto_init() {
	if File_proto_helpdesk_v1_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_helpdesk_v1_admin_proto_rawDesc), len(file_proto_helpdesk_v1_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_helpdesk_v1_admin_proto_goTypes,
		DependencyIndexes: file_proto_helpdesk_v1_admin_proto_depIdxs,
		MessageInfos:      file_proto_helpdesk_v1_admin_proto_msgTypes,
	}.Build()
	File_proto_helpdesk_v1_admin_proto = out.File
	file_proto_helpdesk_v1_admin_proto_goTypes = nil
	file_proto_helpdesk_v1_admin_proto_depIdxs = nil
}
