// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: proto/helpdesk/v1/helpdesk.proto

package helpdesk_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BaseService_Ping_FullMethodName                   = "/v1.BaseService/Ping"
	BaseService_CreateRating_FullMethodName           = "/v1.BaseService/CreateRating"
	BaseService_GetRating_FullMethodName              = "/v1.BaseService/GetRating"
	BaseService_ListRatings_FullMethodName            = "/v1.BaseService/ListRatings"
	BaseService_UpdateRating_FullMethodName           = "/v1.BaseService/UpdateRating"
	BaseService_DeleteRating_FullMethodName           = "/v1.BaseService/DeleteRating"
	BaseService_GetRatingsConfig_FullMethodName       = "/v1.BaseService/GetRatingsConfig"
	BaseService_CreateRatingReply_FullMethodName      = "/v1.BaseService/CreateRatingReply"
	BaseService_ListRatingReplies_FullMethodName      = "/v1.BaseService/ListRatingReplies"
	BaseService_DeleteRatingReply_FullMethodName      = "/v1.BaseService/DeleteRatingReply"
	BaseService_CreateIssue_FullMethodName            = "/v1.BaseService/CreateIssue"
	BaseService_GetIssue_FullMethodName               = "/v1.BaseService/GetIssue"
	BaseService_ListIssues_FullMethodName             = "/v1.BaseService/ListIssues"
	BaseService_UpdateIssue_FullMethodName            = "/v1.BaseService/UpdateIssue"
	BaseService_DeleteIssue_FullMethodName            = "/v1.BaseService/DeleteIssue"
	BaseService_UpdateIssueStatus_FullMethodName      = "/v1.BaseService/UpdateIssueStatus"
	BaseService_ListIssueConfig_FullMethodName        = "/v1.BaseService/ListIssueConfig"
	BaseService_CreateIssueReply_FullMethodName       = "/v1.BaseService/CreateIssueReply"
	BaseService_ListIssueReplies_FullMethodName       = "/v1.BaseService/ListIssueReplies"
	BaseService_DeleteIssueReply_FullMethodName       = "/v1.BaseService/DeleteIssueReply"
	BaseService_GetProduct_FullMethodName             = "/v1.BaseService/GetProduct"
	BaseService_ListProducts_FullMethodName           = "/v1.BaseService/ListProducts"
	BaseService_CreateProduct_FullMethodName          = "/v1.BaseService/CreateProduct"
	BaseService_UpdateProduct_FullMethodName          = "/v1.BaseService/UpdateProduct"
	BaseService_DeleteProduct_FullMethodName          = "/v1.BaseService/DeleteProduct"
	BaseService_ListProductEntities_FullMethodName    = "/v1.BaseService/ListProductEntities"
	BaseService_CreateProductEntity_FullMethodName    = "/v1.BaseService/CreateProductEntity"
	BaseService_DeleteProductEntity_FullMethodName    = "/v1.BaseService/DeleteProductEntity"
	BaseService_ListProductIssueTypes_FullMethodName  = "/v1.BaseService/ListProductIssueTypes"
	BaseService_CreateProductIssueType_FullMethodName = "/v1.BaseService/CreateProductIssueType"
	BaseService_DeleteProductIssueType_FullMethodName = "/v1.BaseService/DeleteProductIssueType"
)

// BaseServiceClient is the client API for BaseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BaseServiceClient interface {
	// Ping is a simple GET request that returns a Pong message.
	Ping(ctx context.Context, in *HDPingRequest, opts ...grpc.CallOption) (*HDPingResponse, error)
	// --- Ratings ---
	CreateRating(ctx context.Context, in *CreateRatingRequest, opts ...grpc.CallOption) (*CreateRatingResponse, error)
	GetRating(ctx context.Context, in *GetRatingRequest, opts ...grpc.CallOption) (*GetRatingResponse, error)
	ListRatings(ctx context.Context, in *ListRatingsRequest, opts ...grpc.CallOption) (*ListRatingsResponse, error)
	UpdateRating(ctx context.Context, in *UpdateRatingRequest, opts ...grpc.CallOption) (*UpdateRatingResponse, error)
	DeleteRating(ctx context.Context, in *DeleteRatingRequest, opts ...grpc.CallOption) (*DeleteRatingResponse, error)
	GetRatingsConfig(ctx context.Context, in *GetRatingsConfigRequest, opts ...grpc.CallOption) (*GetRatingsConfigResponse, error)
	// --- Rating Replies ---
	CreateRatingReply(ctx context.Context, in *CreateRatingReplyRequest, opts ...grpc.CallOption) (*CreateRatingReplyResponse, error)
	ListRatingReplies(ctx context.Context, in *ListRatingRepliesRequest, opts ...grpc.CallOption) (*ListRatingRepliesResponse, error)
	DeleteRatingReply(ctx context.Context, in *DeleteRatingReplyRequest, opts ...grpc.CallOption) (*DeleteRatingReplyResponse, error)
	// --- Issues ---
	CreateIssue(ctx context.Context, in *CreateIssueRequest, opts ...grpc.CallOption) (*CreateIssueResponse, error)
	GetIssue(ctx context.Context, in *GetIssueRequest, opts ...grpc.CallOption) (*GetIssueResponse, error)
	ListIssues(ctx context.Context, in *ListIssuesRequest, opts ...grpc.CallOption) (*ListIssuesResponse, error)
	UpdateIssue(ctx context.Context, in *UpdateIssueRequest, opts ...grpc.CallOption) (*UpdateIssueResponse, error)
	DeleteIssue(ctx context.Context, in *DeleteIssueRequest, opts ...grpc.CallOption) (*DeleteIssueResponse, error)
	UpdateIssueStatus(ctx context.Context, in *UpdateIssueStatusRequest, opts ...grpc.CallOption) (*UpdateIssueStatusResponse, error)
	ListIssueConfig(ctx context.Context, in *ListIssueConfigRequest, opts ...grpc.CallOption) (*ListIssueConfigResponse, error)
	// --- Issue Replies ---
	CreateIssueReply(ctx context.Context, in *CreateIssueReplyRequest, opts ...grpc.CallOption) (*CreateIssueReplyResponse, error)
	ListIssueReplies(ctx context.Context, in *ListIssueRepliesRequest, opts ...grpc.CallOption) (*ListIssueRepliesResponse, error)
	DeleteIssueReply(ctx context.Context, in *DeleteIssueReplyRequest, opts ...grpc.CallOption) (*DeleteIssueReplyResponse, error)
	// --- Admin: Products ---
	GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*GetProductResponse, error)
	ListProducts(ctx context.Context, in *ListProductsRequest, opts ...grpc.CallOption) (*ListProductsResponse, error)
	CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*CreateProductResponse, error)
	UpdateProduct(ctx context.Context, in *UpdateProductRequest, opts ...grpc.CallOption) (*UpdateProductResponse, error)
	DeleteProduct(ctx context.Context, in *DeleteProductRequest, opts ...grpc.CallOption) (*DeleteProductResponse, error)
	// --- Admin: Product Entities ---
	ListProductEntities(ctx context.Context, in *ListProductEntitiesRequest, opts ...grpc.CallOption) (*ListProductEntitiesResponse, error)
	CreateProductEntity(ctx context.Context, in *CreateProductEntityRequest, opts ...grpc.CallOption) (*CreateProductEntityResponse, error)
	DeleteProductEntity(ctx context.Context, in *DeleteProductEntityRequest, opts ...grpc.CallOption) (*DeleteProductEntityResponse, error)
	// --- Admin: Product Issue Types ---
	ListProductIssueTypes(ctx context.Context, in *ListProductIssueTypesRequest, opts ...grpc.CallOption) (*ListProductIssueTypesResponse, error)
	CreateProductIssueType(ctx context.Context, in *CreateProductIssueTypeRequest, opts ...grpc.CallOption) (*CreateProductIssueTypeResponse, error)
	DeleteProductIssueType(ctx context.Context, in *DeleteProductIssueTypeRequest, opts ...grpc.CallOption) (*DeleteProductIssueTypeResponse, error)
}

type baseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBaseServiceClient(cc grpc.ClientConnInterface) BaseServiceClient {
	return &baseServiceClient{cc}
}

func (c *baseServiceClient) Ping(ctx context.Context, in *HDPingRequest, opts ...grpc.CallOption) (*HDPingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HDPingResponse)
	err := c.cc.Invoke(ctx, BaseService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) CreateRating(ctx context.Context, in *CreateRatingRequest, opts ...grpc.CallOption) (*CreateRatingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRatingResponse)
	err := c.cc.Invoke(ctx, BaseService_CreateRating_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) GetRating(ctx context.Context, in *GetRatingRequest, opts ...grpc.CallOption) (*GetRatingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRatingResponse)
	err := c.cc.Invoke(ctx, BaseService_GetRating_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) ListRatings(ctx context.Context, in *ListRatingsRequest, opts ...grpc.CallOption) (*ListRatingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRatingsResponse)
	err := c.cc.Invoke(ctx, BaseService_ListRatings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) UpdateRating(ctx context.Context, in *UpdateRatingRequest, opts ...grpc.CallOption) (*UpdateRatingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRatingResponse)
	err := c.cc.Invoke(ctx, BaseService_UpdateRating_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) DeleteRating(ctx context.Context, in *DeleteRatingRequest, opts ...grpc.CallOption) (*DeleteRatingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRatingResponse)
	err := c.cc.Invoke(ctx, BaseService_DeleteRating_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) GetRatingsConfig(ctx context.Context, in *GetRatingsConfigRequest, opts ...grpc.CallOption) (*GetRatingsConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRatingsConfigResponse)
	err := c.cc.Invoke(ctx, BaseService_GetRatingsConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) CreateRatingReply(ctx context.Context, in *CreateRatingReplyRequest, opts ...grpc.CallOption) (*CreateRatingReplyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRatingReplyResponse)
	err := c.cc.Invoke(ctx, BaseService_CreateRatingReply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) ListRatingReplies(ctx context.Context, in *ListRatingRepliesRequest, opts ...grpc.CallOption) (*ListRatingRepliesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRatingRepliesResponse)
	err := c.cc.Invoke(ctx, BaseService_ListRatingReplies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) DeleteRatingReply(ctx context.Context, in *DeleteRatingReplyRequest, opts ...grpc.CallOption) (*DeleteRatingReplyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRatingReplyResponse)
	err := c.cc.Invoke(ctx, BaseService_DeleteRatingReply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) CreateIssue(ctx context.Context, in *CreateIssueRequest, opts ...grpc.CallOption) (*CreateIssueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateIssueResponse)
	err := c.cc.Invoke(ctx, BaseService_CreateIssue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) GetIssue(ctx context.Context, in *GetIssueRequest, opts ...grpc.CallOption) (*GetIssueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIssueResponse)
	err := c.cc.Invoke(ctx, BaseService_GetIssue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) ListIssues(ctx context.Context, in *ListIssuesRequest, opts ...grpc.CallOption) (*ListIssuesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListIssuesResponse)
	err := c.cc.Invoke(ctx, BaseService_ListIssues_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) UpdateIssue(ctx context.Context, in *UpdateIssueRequest, opts ...grpc.CallOption) (*UpdateIssueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateIssueResponse)
	err := c.cc.Invoke(ctx, BaseService_UpdateIssue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) DeleteIssue(ctx context.Context, in *DeleteIssueRequest, opts ...grpc.CallOption) (*DeleteIssueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteIssueResponse)
	err := c.cc.Invoke(ctx, BaseService_DeleteIssue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) UpdateIssueStatus(ctx context.Context, in *UpdateIssueStatusRequest, opts ...grpc.CallOption) (*UpdateIssueStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateIssueStatusResponse)
	err := c.cc.Invoke(ctx, BaseService_UpdateIssueStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) ListIssueConfig(ctx context.Context, in *ListIssueConfigRequest, opts ...grpc.CallOption) (*ListIssueConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListIssueConfigResponse)
	err := c.cc.Invoke(ctx, BaseService_ListIssueConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) CreateIssueReply(ctx context.Context, in *CreateIssueReplyRequest, opts ...grpc.CallOption) (*CreateIssueReplyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateIssueReplyResponse)
	err := c.cc.Invoke(ctx, BaseService_CreateIssueReply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) ListIssueReplies(ctx context.Context, in *ListIssueRepliesRequest, opts ...grpc.CallOption) (*ListIssueRepliesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListIssueRepliesResponse)
	err := c.cc.Invoke(ctx, BaseService_ListIssueReplies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) DeleteIssueReply(ctx context.Context, in *DeleteIssueReplyRequest, opts ...grpc.CallOption) (*DeleteIssueReplyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteIssueReplyResponse)
	err := c.cc.Invoke(ctx, BaseService_DeleteIssueReply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*GetProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProductResponse)
	err := c.cc.Invoke(ctx, BaseService_GetProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) ListProducts(ctx context.Context, in *ListProductsRequest, opts ...grpc.CallOption) (*ListProductsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProductsResponse)
	err := c.cc.Invoke(ctx, BaseService_ListProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*CreateProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateProductResponse)
	err := c.cc.Invoke(ctx, BaseService_CreateProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) UpdateProduct(ctx context.Context, in *UpdateProductRequest, opts ...grpc.CallOption) (*UpdateProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateProductResponse)
	err := c.cc.Invoke(ctx, BaseService_UpdateProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) DeleteProduct(ctx context.Context, in *DeleteProductRequest, opts ...grpc.CallOption) (*DeleteProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteProductResponse)
	err := c.cc.Invoke(ctx, BaseService_DeleteProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) ListProductEntities(ctx context.Context, in *ListProductEntitiesRequest, opts ...grpc.CallOption) (*ListProductEntitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProductEntitiesResponse)
	err := c.cc.Invoke(ctx, BaseService_ListProductEntities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) CreateProductEntity(ctx context.Context, in *CreateProductEntityRequest, opts ...grpc.CallOption) (*CreateProductEntityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateProductEntityResponse)
	err := c.cc.Invoke(ctx, BaseService_CreateProductEntity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) DeleteProductEntity(ctx context.Context, in *DeleteProductEntityRequest, opts ...grpc.CallOption) (*DeleteProductEntityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteProductEntityResponse)
	err := c.cc.Invoke(ctx, BaseService_DeleteProductEntity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) ListProductIssueTypes(ctx context.Context, in *ListProductIssueTypesRequest, opts ...grpc.CallOption) (*ListProductIssueTypesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProductIssueTypesResponse)
	err := c.cc.Invoke(ctx, BaseService_ListProductIssueTypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) CreateProductIssueType(ctx context.Context, in *CreateProductIssueTypeRequest, opts ...grpc.CallOption) (*CreateProductIssueTypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateProductIssueTypeResponse)
	err := c.cc.Invoke(ctx, BaseService_CreateProductIssueType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) DeleteProductIssueType(ctx context.Context, in *DeleteProductIssueTypeRequest, opts ...grpc.CallOption) (*DeleteProductIssueTypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteProductIssueTypeResponse)
	err := c.cc.Invoke(ctx, BaseService_DeleteProductIssueType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BaseServiceServer is the server API for BaseService service.
// All implementations must embed UnimplementedBaseServiceServer
// for forward compatibility.
type BaseServiceServer interface {
	// Ping is a simple GET request that returns a Pong message.
	Ping(context.Context, *HDPingRequest) (*HDPingResponse, error)
	// --- Ratings ---
	CreateRating(context.Context, *CreateRatingRequest) (*CreateRatingResponse, error)
	GetRating(context.Context, *GetRatingRequest) (*GetRatingResponse, error)
	ListRatings(context.Context, *ListRatingsRequest) (*ListRatingsResponse, error)
	UpdateRating(context.Context, *UpdateRatingRequest) (*UpdateRatingResponse, error)
	DeleteRating(context.Context, *DeleteRatingRequest) (*DeleteRatingResponse, error)
	GetRatingsConfig(context.Context, *GetRatingsConfigRequest) (*GetRatingsConfigResponse, error)
	// --- Rating Replies ---
	CreateRatingReply(context.Context, *CreateRatingReplyRequest) (*CreateRatingReplyResponse, error)
	ListRatingReplies(context.Context, *ListRatingRepliesRequest) (*ListRatingRepliesResponse, error)
	DeleteRatingReply(context.Context, *DeleteRatingReplyRequest) (*DeleteRatingReplyResponse, error)
	// --- Issues ---
	CreateIssue(context.Context, *CreateIssueRequest) (*CreateIssueResponse, error)
	GetIssue(context.Context, *GetIssueRequest) (*GetIssueResponse, error)
	ListIssues(context.Context, *ListIssuesRequest) (*ListIssuesResponse, error)
	UpdateIssue(context.Context, *UpdateIssueRequest) (*UpdateIssueResponse, error)
	DeleteIssue(context.Context, *DeleteIssueRequest) (*DeleteIssueResponse, error)
	UpdateIssueStatus(context.Context, *UpdateIssueStatusRequest) (*UpdateIssueStatusResponse, error)
	ListIssueConfig(context.Context, *ListIssueConfigRequest) (*ListIssueConfigResponse, error)
	// --- Issue Replies ---
	CreateIssueReply(context.Context, *CreateIssueReplyRequest) (*CreateIssueReplyResponse, error)
	ListIssueReplies(context.Context, *ListIssueRepliesRequest) (*ListIssueRepliesResponse, error)
	DeleteIssueReply(context.Context, *DeleteIssueReplyRequest) (*DeleteIssueReplyResponse, error)
	// --- Admin: Products ---
	GetProduct(context.Context, *GetProductRequest) (*GetProductResponse, error)
	ListProducts(context.Context, *ListProductsRequest) (*ListProductsResponse, error)
	CreateProduct(context.Context, *CreateProductRequest) (*CreateProductResponse, error)
	UpdateProduct(context.Context, *UpdateProductRequest) (*UpdateProductResponse, error)
	DeleteProduct(context.Context, *DeleteProductRequest) (*DeleteProductResponse, error)
	// --- Admin: Product Entities ---
	ListProductEntities(context.Context, *ListProductEntitiesRequest) (*ListProductEntitiesResponse, error)
	CreateProductEntity(context.Context, *CreateProductEntityRequest) (*CreateProductEntityResponse, error)
	DeleteProductEntity(context.Context, *DeleteProductEntityRequest) (*DeleteProductEntityResponse, error)
	// --- Admin: Product Issue Types ---
	ListProductIssueTypes(context.Context, *ListProductIssueTypesRequest) (*ListProductIssueTypesResponse, error)
	CreateProductIssueType(context.Context, *CreateProductIssueTypeRequest) (*CreateProductIssueTypeResponse, error)
	DeleteProductIssueType(context.Context, *DeleteProductIssueTypeRequest) (*DeleteProductIssueTypeResponse, error)
	mustEmbedUnimplementedBaseServiceServer()
}

// UnimplementedBaseServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBaseServiceServer struct{}

func (UnimplementedBaseServiceServer) Ping(context.Context, *HDPingRequest) (*HDPingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedBaseServiceServer) CreateRating(context.Context, *CreateRatingRequest) (*CreateRatingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRating not implemented")
}
func (UnimplementedBaseServiceServer) GetRating(context.Context, *GetRatingRequest) (*GetRatingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRating not implemented")
}
func (UnimplementedBaseServiceServer) ListRatings(context.Context, *ListRatingsRequest) (*ListRatingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRatings not implemented")
}
func (UnimplementedBaseServiceServer) UpdateRating(context.Context, *UpdateRatingRequest) (*UpdateRatingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRating not implemented")
}
func (UnimplementedBaseServiceServer) DeleteRating(context.Context, *DeleteRatingRequest) (*DeleteRatingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRating not implemented")
}
func (UnimplementedBaseServiceServer) GetRatingsConfig(context.Context, *GetRatingsConfigRequest) (*GetRatingsConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRatingsConfig not implemented")
}
func (UnimplementedBaseServiceServer) CreateRatingReply(context.Context, *CreateRatingReplyRequest) (*CreateRatingReplyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRatingReply not implemented")
}
func (UnimplementedBaseServiceServer) ListRatingReplies(context.Context, *ListRatingRepliesRequest) (*ListRatingRepliesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRatingReplies not implemented")
}
func (UnimplementedBaseServiceServer) DeleteRatingReply(context.Context, *DeleteRatingReplyRequest) (*DeleteRatingReplyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRatingReply not implemented")
}
func (UnimplementedBaseServiceServer) CreateIssue(context.Context, *CreateIssueRequest) (*CreateIssueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateIssue not implemented")
}
func (UnimplementedBaseServiceServer) GetIssue(context.Context, *GetIssueRequest) (*GetIssueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIssue not implemented")
}
func (UnimplementedBaseServiceServer) ListIssues(context.Context, *ListIssuesRequest) (*ListIssuesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListIssues not implemented")
}
func (UnimplementedBaseServiceServer) UpdateIssue(context.Context, *UpdateIssueRequest) (*UpdateIssueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateIssue not implemented")
}
func (UnimplementedBaseServiceServer) DeleteIssue(context.Context, *DeleteIssueRequest) (*DeleteIssueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteIssue not implemented")
}
func (UnimplementedBaseServiceServer) UpdateIssueStatus(context.Context, *UpdateIssueStatusRequest) (*UpdateIssueStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateIssueStatus not implemented")
}
func (UnimplementedBaseServiceServer) ListIssueConfig(context.Context, *ListIssueConfigRequest) (*ListIssueConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListIssueConfig not implemented")
}
func (UnimplementedBaseServiceServer) CreateIssueReply(context.Context, *CreateIssueReplyRequest) (*CreateIssueReplyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateIssueReply not implemented")
}
func (UnimplementedBaseServiceServer) ListIssueReplies(context.Context, *ListIssueRepliesRequest) (*ListIssueRepliesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListIssueReplies not implemented")
}
func (UnimplementedBaseServiceServer) DeleteIssueReply(context.Context, *DeleteIssueReplyRequest) (*DeleteIssueReplyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteIssueReply not implemented")
}
func (UnimplementedBaseServiceServer) GetProduct(context.Context, *GetProductRequest) (*GetProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProduct not implemented")
}
func (UnimplementedBaseServiceServer) ListProducts(context.Context, *ListProductsRequest) (*ListProductsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProducts not implemented")
}
func (UnimplementedBaseServiceServer) CreateProduct(context.Context, *CreateProductRequest) (*CreateProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProduct not implemented")
}
func (UnimplementedBaseServiceServer) UpdateProduct(context.Context, *UpdateProductRequest) (*UpdateProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProduct not implemented")
}
func (UnimplementedBaseServiceServer) DeleteProduct(context.Context, *DeleteProductRequest) (*DeleteProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProduct not implemented")
}
func (UnimplementedBaseServiceServer) ListProductEntities(context.Context, *ListProductEntitiesRequest) (*ListProductEntitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProductEntities not implemented")
}
func (UnimplementedBaseServiceServer) CreateProductEntity(context.Context, *CreateProductEntityRequest) (*CreateProductEntityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProductEntity not implemented")
}
func (UnimplementedBaseServiceServer) DeleteProductEntity(context.Context, *DeleteProductEntityRequest) (*DeleteProductEntityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProductEntity not implemented")
}
func (UnimplementedBaseServiceServer) ListProductIssueTypes(context.Context, *ListProductIssueTypesRequest) (*ListProductIssueTypesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProductIssueTypes not implemented")
}
func (UnimplementedBaseServiceServer) CreateProductIssueType(context.Context, *CreateProductIssueTypeRequest) (*CreateProductIssueTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProductIssueType not implemented")
}
func (UnimplementedBaseServiceServer) DeleteProductIssueType(context.Context, *DeleteProductIssueTypeRequest) (*DeleteProductIssueTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProductIssueType not implemented")
}
func (UnimplementedBaseServiceServer) mustEmbedUnimplementedBaseServiceServer() {}
func (UnimplementedBaseServiceServer) testEmbeddedByValue()                     {}

// UnsafeBaseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BaseServiceServer will
// result in compilation errors.
type UnsafeBaseServiceServer interface {
	mustEmbedUnimplementedBaseServiceServer()
}

func RegisterBaseServiceServer(s grpc.ServiceRegistrar, srv BaseServiceServer) {
	// If the following call pancis, it indicates UnimplementedBaseServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BaseService_ServiceDesc, srv)
}

func _BaseService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HDPingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).Ping(ctx, req.(*HDPingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_CreateRating_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRatingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).CreateRating(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_CreateRating_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).CreateRating(ctx, req.(*CreateRatingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_GetRating_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRatingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).GetRating(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_GetRating_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).GetRating(ctx, req.(*GetRatingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_ListRatings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRatingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).ListRatings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_ListRatings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).ListRatings(ctx, req.(*ListRatingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_UpdateRating_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRatingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).UpdateRating(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_UpdateRating_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).UpdateRating(ctx, req.(*UpdateRatingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_DeleteRating_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRatingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).DeleteRating(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_DeleteRating_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).DeleteRating(ctx, req.(*DeleteRatingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_GetRatingsConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRatingsConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).GetRatingsConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_GetRatingsConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).GetRatingsConfig(ctx, req.(*GetRatingsConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_CreateRatingReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRatingReplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).CreateRatingReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_CreateRatingReply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).CreateRatingReply(ctx, req.(*CreateRatingReplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_ListRatingReplies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRatingRepliesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).ListRatingReplies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_ListRatingReplies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).ListRatingReplies(ctx, req.(*ListRatingRepliesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_DeleteRatingReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRatingReplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).DeleteRatingReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_DeleteRatingReply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).DeleteRatingReply(ctx, req.(*DeleteRatingReplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_CreateIssue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateIssueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).CreateIssue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_CreateIssue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).CreateIssue(ctx, req.(*CreateIssueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_GetIssue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIssueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).GetIssue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_GetIssue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).GetIssue(ctx, req.(*GetIssueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_ListIssues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListIssuesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).ListIssues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_ListIssues_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).ListIssues(ctx, req.(*ListIssuesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_UpdateIssue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateIssueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).UpdateIssue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_UpdateIssue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).UpdateIssue(ctx, req.(*UpdateIssueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_DeleteIssue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteIssueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).DeleteIssue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_DeleteIssue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).DeleteIssue(ctx, req.(*DeleteIssueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_UpdateIssueStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateIssueStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).UpdateIssueStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_UpdateIssueStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).UpdateIssueStatus(ctx, req.(*UpdateIssueStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_ListIssueConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListIssueConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).ListIssueConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_ListIssueConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).ListIssueConfig(ctx, req.(*ListIssueConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_CreateIssueReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateIssueReplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).CreateIssueReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_CreateIssueReply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).CreateIssueReply(ctx, req.(*CreateIssueReplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_ListIssueReplies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListIssueRepliesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).ListIssueReplies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_ListIssueReplies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).ListIssueReplies(ctx, req.(*ListIssueRepliesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_DeleteIssueReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteIssueReplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).DeleteIssueReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_DeleteIssueReply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).DeleteIssueReply(ctx, req.(*DeleteIssueReplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_GetProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).GetProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_GetProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).GetProduct(ctx, req.(*GetProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_ListProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).ListProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_ListProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).ListProducts(ctx, req.(*ListProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_CreateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).CreateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_CreateProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).CreateProduct(ctx, req.(*CreateProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_UpdateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).UpdateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_UpdateProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).UpdateProduct(ctx, req.(*UpdateProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_DeleteProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).DeleteProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_DeleteProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).DeleteProduct(ctx, req.(*DeleteProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_ListProductEntities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProductEntitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).ListProductEntities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_ListProductEntities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).ListProductEntities(ctx, req.(*ListProductEntitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_CreateProductEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProductEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).CreateProductEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_CreateProductEntity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).CreateProductEntity(ctx, req.(*CreateProductEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_DeleteProductEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProductEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).DeleteProductEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_DeleteProductEntity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).DeleteProductEntity(ctx, req.(*DeleteProductEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_ListProductIssueTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProductIssueTypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).ListProductIssueTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_ListProductIssueTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).ListProductIssueTypes(ctx, req.(*ListProductIssueTypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_CreateProductIssueType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProductIssueTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).CreateProductIssueType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_CreateProductIssueType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).CreateProductIssueType(ctx, req.(*CreateProductIssueTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_DeleteProductIssueType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProductIssueTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).DeleteProductIssueType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_DeleteProductIssueType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).DeleteProductIssueType(ctx, req.(*DeleteProductIssueTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BaseService_ServiceDesc is the grpc.ServiceDesc for BaseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BaseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.BaseService",
	HandlerType: (*BaseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _BaseService_Ping_Handler,
		},
		{
			MethodName: "CreateRating",
			Handler:    _BaseService_CreateRating_Handler,
		},
		{
			MethodName: "GetRating",
			Handler:    _BaseService_GetRating_Handler,
		},
		{
			MethodName: "ListRatings",
			Handler:    _BaseService_ListRatings_Handler,
		},
		{
			MethodName: "UpdateRating",
			Handler:    _BaseService_UpdateRating_Handler,
		},
		{
			MethodName: "DeleteRating",
			Handler:    _BaseService_DeleteRating_Handler,
		},
		{
			MethodName: "GetRatingsConfig",
			Handler:    _BaseService_GetRatingsConfig_Handler,
		},
		{
			MethodName: "CreateRatingReply",
			Handler:    _BaseService_CreateRatingReply_Handler,
		},
		{
			MethodName: "ListRatingReplies",
			Handler:    _BaseService_ListRatingReplies_Handler,
		},
		{
			MethodName: "DeleteRatingReply",
			Handler:    _BaseService_DeleteRatingReply_Handler,
		},
		{
			MethodName: "CreateIssue",
			Handler:    _BaseService_CreateIssue_Handler,
		},
		{
			MethodName: "GetIssue",
			Handler:    _BaseService_GetIssue_Handler,
		},
		{
			MethodName: "ListIssues",
			Handler:    _BaseService_ListIssues_Handler,
		},
		{
			MethodName: "UpdateIssue",
			Handler:    _BaseService_UpdateIssue_Handler,
		},
		{
			MethodName: "DeleteIssue",
			Handler:    _BaseService_DeleteIssue_Handler,
		},
		{
			MethodName: "UpdateIssueStatus",
			Handler:    _BaseService_UpdateIssueStatus_Handler,
		},
		{
			MethodName: "ListIssueConfig",
			Handler:    _BaseService_ListIssueConfig_Handler,
		},
		{
			MethodName: "CreateIssueReply",
			Handler:    _BaseService_CreateIssueReply_Handler,
		},
		{
			MethodName: "ListIssueReplies",
			Handler:    _BaseService_ListIssueReplies_Handler,
		},
		{
			MethodName: "DeleteIssueReply",
			Handler:    _BaseService_DeleteIssueReply_Handler,
		},
		{
			MethodName: "GetProduct",
			Handler:    _BaseService_GetProduct_Handler,
		},
		{
			MethodName: "ListProducts",
			Handler:    _BaseService_ListProducts_Handler,
		},
		{
			MethodName: "CreateProduct",
			Handler:    _BaseService_CreateProduct_Handler,
		},
		{
			MethodName: "UpdateProduct",
			Handler:    _BaseService_UpdateProduct_Handler,
		},
		{
			MethodName: "DeleteProduct",
			Handler:    _BaseService_DeleteProduct_Handler,
		},
		{
			MethodName: "ListProductEntities",
			Handler:    _BaseService_ListProductEntities_Handler,
		},
		{
			MethodName: "CreateProductEntity",
			Handler:    _BaseService_CreateProductEntity_Handler,
		},
		{
			MethodName: "DeleteProductEntity",
			Handler:    _BaseService_DeleteProductEntity_Handler,
		},
		{
			MethodName: "ListProductIssueTypes",
			Handler:    _BaseService_ListProductIssueTypes_Handler,
		},
		{
			MethodName: "CreateProductIssueType",
			Handler:    _BaseService_CreateProductIssueType_Handler,
		},
		{
			MethodName: "DeleteProductIssueType",
			Handler:    _BaseService_DeleteProductIssueType_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/helpdesk/v1/helpdesk.proto",
}
