// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: proto/helpdesk/v1/issues.proto

package helpdesk_v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Issue with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Issue) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Issue with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in IssueMultiError, or nil if none found.
func (m *Issue) ValidateAll() error {
	return m.validate(true)
}

func (m *Issue) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for UserId

	// no validation rules for ProductId

	// no validation rules for Entity

	// no validation rules for EntityId

	// no validation rules for Title

	// no validation rules for Description

	// no validation rules for Status

	// no validation rules for CreatedAt

	// no validation rules for UpdatedAt

	if len(errors) > 0 {
		return IssueMultiError(errors)
	}

	return nil
}

// IssueMultiError is an error wrapping multiple validation errors returned by
// Issue.ValidateAll() if the designated constraints aren't met.
type IssueMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m IssueMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m IssueMultiError) AllErrors() []error { return m }

// IssueValidationError is the validation error returned by Issue.Validate if
// the designated constraints aren't met.
type IssueValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e IssueValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e IssueValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e IssueValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e IssueValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e IssueValidationError) ErrorName() string { return "IssueValidationError" }

// Error satisfies the builtin error interface
func (e IssueValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sIssue.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = IssueValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = IssueValidationError{}

// Validate checks the field values on IssueReply with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *IssueReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on IssueReply with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in IssueReplyMultiError, or
// nil if none found.
func (m *IssueReply) ValidateAll() error {
	return m.validate(true)
}

func (m *IssueReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for IssueId

	// no validation rules for UserId

	// no validation rules for Role

	// no validation rules for Message

	// no validation rules for IsDeleted

	// no validation rules for CreatedAt

	if len(errors) > 0 {
		return IssueReplyMultiError(errors)
	}

	return nil
}

// IssueReplyMultiError is an error wrapping multiple validation errors
// returned by IssueReply.ValidateAll() if the designated constraints aren't met.
type IssueReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m IssueReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m IssueReplyMultiError) AllErrors() []error { return m }

// IssueReplyValidationError is the validation error returned by
// IssueReply.Validate if the designated constraints aren't met.
type IssueReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e IssueReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e IssueReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e IssueReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e IssueReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e IssueReplyValidationError) ErrorName() string { return "IssueReplyValidationError" }

// Error satisfies the builtin error interface
func (e IssueReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sIssueReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = IssueReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = IssueReplyValidationError{}

// Validate checks the field values on CreateIssueRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateIssueRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateIssueRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateIssueRequestMultiError, or nil if none found.
func (m *CreateIssueRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateIssueRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ProductId

	// no validation rules for Entity

	// no validation rules for EntityId

	// no validation rules for Title

	// no validation rules for Description

	if len(errors) > 0 {
		return CreateIssueRequestMultiError(errors)
	}

	return nil
}

// CreateIssueRequestMultiError is an error wrapping multiple validation errors
// returned by CreateIssueRequest.ValidateAll() if the designated constraints
// aren't met.
type CreateIssueRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateIssueRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateIssueRequestMultiError) AllErrors() []error { return m }

// CreateIssueRequestValidationError is the validation error returned by
// CreateIssueRequest.Validate if the designated constraints aren't met.
type CreateIssueRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateIssueRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateIssueRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateIssueRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateIssueRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateIssueRequestValidationError) ErrorName() string {
	return "CreateIssueRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateIssueRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateIssueRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateIssueRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateIssueRequestValidationError{}

// Validate checks the field values on CreateIssueResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateIssueResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateIssueResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateIssueResponseMultiError, or nil if none found.
func (m *CreateIssueResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateIssueResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetIssue()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateIssueResponseValidationError{
					field:  "Issue",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateIssueResponseValidationError{
					field:  "Issue",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetIssue()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateIssueResponseValidationError{
				field:  "Issue",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateIssueResponseMultiError(errors)
	}

	return nil
}

// CreateIssueResponseMultiError is an error wrapping multiple validation
// errors returned by CreateIssueResponse.ValidateAll() if the designated
// constraints aren't met.
type CreateIssueResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateIssueResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateIssueResponseMultiError) AllErrors() []error { return m }

// CreateIssueResponseValidationError is the validation error returned by
// CreateIssueResponse.Validate if the designated constraints aren't met.
type CreateIssueResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateIssueResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateIssueResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateIssueResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateIssueResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateIssueResponseValidationError) ErrorName() string {
	return "CreateIssueResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateIssueResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateIssueResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateIssueResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateIssueResponseValidationError{}

// Validate checks the field values on GetIssueRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetIssueRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetIssueRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetIssueRequestMultiError, or nil if none found.
func (m *GetIssueRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetIssueRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return GetIssueRequestMultiError(errors)
	}

	return nil
}

// GetIssueRequestMultiError is an error wrapping multiple validation errors
// returned by GetIssueRequest.ValidateAll() if the designated constraints
// aren't met.
type GetIssueRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetIssueRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetIssueRequestMultiError) AllErrors() []error { return m }

// GetIssueRequestValidationError is the validation error returned by
// GetIssueRequest.Validate if the designated constraints aren't met.
type GetIssueRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetIssueRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetIssueRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetIssueRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetIssueRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetIssueRequestValidationError) ErrorName() string { return "GetIssueRequestValidationError" }

// Error satisfies the builtin error interface
func (e GetIssueRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetIssueRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetIssueRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetIssueRequestValidationError{}

// Validate checks the field values on GetIssueResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetIssueResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetIssueResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetIssueResponseMultiError, or nil if none found.
func (m *GetIssueResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetIssueResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetIssue()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetIssueResponseValidationError{
					field:  "Issue",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetIssueResponseValidationError{
					field:  "Issue",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetIssue()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetIssueResponseValidationError{
				field:  "Issue",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetIssueResponseMultiError(errors)
	}

	return nil
}

// GetIssueResponseMultiError is an error wrapping multiple validation errors
// returned by GetIssueResponse.ValidateAll() if the designated constraints
// aren't met.
type GetIssueResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetIssueResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetIssueResponseMultiError) AllErrors() []error { return m }

// GetIssueResponseValidationError is the validation error returned by
// GetIssueResponse.Validate if the designated constraints aren't met.
type GetIssueResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetIssueResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetIssueResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetIssueResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetIssueResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetIssueResponseValidationError) ErrorName() string { return "GetIssueResponseValidationError" }

// Error satisfies the builtin error interface
func (e GetIssueResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetIssueResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetIssueResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetIssueResponseValidationError{}

// Validate checks the field values on ListIssuesRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ListIssuesRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListIssuesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListIssuesRequestMultiError, or nil if none found.
func (m *ListIssuesRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListIssuesRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for UserId

	// no validation rules for Entity

	// no validation rules for EntityId

	// no validation rules for Status

	// no validation rules for Page

	// no validation rules for PageSize

	if len(errors) > 0 {
		return ListIssuesRequestMultiError(errors)
	}

	return nil
}

// ListIssuesRequestMultiError is an error wrapping multiple validation errors
// returned by ListIssuesRequest.ValidateAll() if the designated constraints
// aren't met.
type ListIssuesRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListIssuesRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListIssuesRequestMultiError) AllErrors() []error { return m }

// ListIssuesRequestValidationError is the validation error returned by
// ListIssuesRequest.Validate if the designated constraints aren't met.
type ListIssuesRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListIssuesRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListIssuesRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListIssuesRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListIssuesRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListIssuesRequestValidationError) ErrorName() string {
	return "ListIssuesRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListIssuesRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListIssuesRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListIssuesRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListIssuesRequestValidationError{}

// Validate checks the field values on ListIssuesResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListIssuesResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListIssuesResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListIssuesResponseMultiError, or nil if none found.
func (m *ListIssuesResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListIssuesResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetIssues() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListIssuesResponseValidationError{
						field:  fmt.Sprintf("Issues[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListIssuesResponseValidationError{
						field:  fmt.Sprintf("Issues[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListIssuesResponseValidationError{
					field:  fmt.Sprintf("Issues[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListIssuesResponseMultiError(errors)
	}

	return nil
}

// ListIssuesResponseMultiError is an error wrapping multiple validation errors
// returned by ListIssuesResponse.ValidateAll() if the designated constraints
// aren't met.
type ListIssuesResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListIssuesResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListIssuesResponseMultiError) AllErrors() []error { return m }

// ListIssuesResponseValidationError is the validation error returned by
// ListIssuesResponse.Validate if the designated constraints aren't met.
type ListIssuesResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListIssuesResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListIssuesResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListIssuesResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListIssuesResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListIssuesResponseValidationError) ErrorName() string {
	return "ListIssuesResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListIssuesResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListIssuesResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListIssuesResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListIssuesResponseValidationError{}

// Validate checks the field values on UpdateIssueRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateIssueRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateIssueRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateIssueRequestMultiError, or nil if none found.
func (m *UpdateIssueRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateIssueRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Title

	// no validation rules for Description

	// no validation rules for Status

	if len(errors) > 0 {
		return UpdateIssueRequestMultiError(errors)
	}

	return nil
}

// UpdateIssueRequestMultiError is an error wrapping multiple validation errors
// returned by UpdateIssueRequest.ValidateAll() if the designated constraints
// aren't met.
type UpdateIssueRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateIssueRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateIssueRequestMultiError) AllErrors() []error { return m }

// UpdateIssueRequestValidationError is the validation error returned by
// UpdateIssueRequest.Validate if the designated constraints aren't met.
type UpdateIssueRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateIssueRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateIssueRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateIssueRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateIssueRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateIssueRequestValidationError) ErrorName() string {
	return "UpdateIssueRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateIssueRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateIssueRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateIssueRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateIssueRequestValidationError{}

// Validate checks the field values on UpdateIssueResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateIssueResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateIssueResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateIssueResponseMultiError, or nil if none found.
func (m *UpdateIssueResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateIssueResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetIssue()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateIssueResponseValidationError{
					field:  "Issue",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateIssueResponseValidationError{
					field:  "Issue",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetIssue()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateIssueResponseValidationError{
				field:  "Issue",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UpdateIssueResponseMultiError(errors)
	}

	return nil
}

// UpdateIssueResponseMultiError is an error wrapping multiple validation
// errors returned by UpdateIssueResponse.ValidateAll() if the designated
// constraints aren't met.
type UpdateIssueResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateIssueResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateIssueResponseMultiError) AllErrors() []error { return m }

// UpdateIssueResponseValidationError is the validation error returned by
// UpdateIssueResponse.Validate if the designated constraints aren't met.
type UpdateIssueResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateIssueResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateIssueResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateIssueResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateIssueResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateIssueResponseValidationError) ErrorName() string {
	return "UpdateIssueResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateIssueResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateIssueResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateIssueResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateIssueResponseValidationError{}

// Validate checks the field values on DeleteIssueRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteIssueRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteIssueRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteIssueRequestMultiError, or nil if none found.
func (m *DeleteIssueRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteIssueRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return DeleteIssueRequestMultiError(errors)
	}

	return nil
}

// DeleteIssueRequestMultiError is an error wrapping multiple validation errors
// returned by DeleteIssueRequest.ValidateAll() if the designated constraints
// aren't met.
type DeleteIssueRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteIssueRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteIssueRequestMultiError) AllErrors() []error { return m }

// DeleteIssueRequestValidationError is the validation error returned by
// DeleteIssueRequest.Validate if the designated constraints aren't met.
type DeleteIssueRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteIssueRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteIssueRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteIssueRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteIssueRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteIssueRequestValidationError) ErrorName() string {
	return "DeleteIssueRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteIssueRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteIssueRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteIssueRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteIssueRequestValidationError{}

// Validate checks the field values on DeleteIssueResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteIssueResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteIssueResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteIssueResponseMultiError, or nil if none found.
func (m *DeleteIssueResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteIssueResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Success

	if len(errors) > 0 {
		return DeleteIssueResponseMultiError(errors)
	}

	return nil
}

// DeleteIssueResponseMultiError is an error wrapping multiple validation
// errors returned by DeleteIssueResponse.ValidateAll() if the designated
// constraints aren't met.
type DeleteIssueResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteIssueResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteIssueResponseMultiError) AllErrors() []error { return m }

// DeleteIssueResponseValidationError is the validation error returned by
// DeleteIssueResponse.Validate if the designated constraints aren't met.
type DeleteIssueResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteIssueResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteIssueResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteIssueResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteIssueResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteIssueResponseValidationError) ErrorName() string {
	return "DeleteIssueResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteIssueResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteIssueResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteIssueResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteIssueResponseValidationError{}

// Validate checks the field values on CreateIssueReplyRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateIssueReplyRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateIssueReplyRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateIssueReplyRequestMultiError, or nil if none found.
func (m *CreateIssueReplyRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateIssueReplyRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for IssueId

	// no validation rules for Message

	if len(errors) > 0 {
		return CreateIssueReplyRequestMultiError(errors)
	}

	return nil
}

// CreateIssueReplyRequestMultiError is an error wrapping multiple validation
// errors returned by CreateIssueReplyRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateIssueReplyRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateIssueReplyRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateIssueReplyRequestMultiError) AllErrors() []error { return m }

// CreateIssueReplyRequestValidationError is the validation error returned by
// CreateIssueReplyRequest.Validate if the designated constraints aren't met.
type CreateIssueReplyRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateIssueReplyRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateIssueReplyRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateIssueReplyRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateIssueReplyRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateIssueReplyRequestValidationError) ErrorName() string {
	return "CreateIssueReplyRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateIssueReplyRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateIssueReplyRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateIssueReplyRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateIssueReplyRequestValidationError{}

// Validate checks the field values on CreateIssueReplyResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateIssueReplyResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateIssueReplyResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateIssueReplyResponseMultiError, or nil if none found.
func (m *CreateIssueReplyResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateIssueReplyResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetReply()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateIssueReplyResponseValidationError{
					field:  "Reply",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateIssueReplyResponseValidationError{
					field:  "Reply",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetReply()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateIssueReplyResponseValidationError{
				field:  "Reply",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateIssueReplyResponseMultiError(errors)
	}

	return nil
}

// CreateIssueReplyResponseMultiError is an error wrapping multiple validation
// errors returned by CreateIssueReplyResponse.ValidateAll() if the designated
// constraints aren't met.
type CreateIssueReplyResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateIssueReplyResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateIssueReplyResponseMultiError) AllErrors() []error { return m }

// CreateIssueReplyResponseValidationError is the validation error returned by
// CreateIssueReplyResponse.Validate if the designated constraints aren't met.
type CreateIssueReplyResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateIssueReplyResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateIssueReplyResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateIssueReplyResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateIssueReplyResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateIssueReplyResponseValidationError) ErrorName() string {
	return "CreateIssueReplyResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateIssueReplyResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateIssueReplyResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateIssueReplyResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateIssueReplyResponseValidationError{}

// Validate checks the field values on ListIssueRepliesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListIssueRepliesRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListIssueRepliesRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListIssueRepliesRequestMultiError, or nil if none found.
func (m *ListIssueRepliesRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListIssueRepliesRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for IssueId

	// no validation rules for Page

	// no validation rules for PageSize

	if len(errors) > 0 {
		return ListIssueRepliesRequestMultiError(errors)
	}

	return nil
}

// ListIssueRepliesRequestMultiError is an error wrapping multiple validation
// errors returned by ListIssueRepliesRequest.ValidateAll() if the designated
// constraints aren't met.
type ListIssueRepliesRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListIssueRepliesRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListIssueRepliesRequestMultiError) AllErrors() []error { return m }

// ListIssueRepliesRequestValidationError is the validation error returned by
// ListIssueRepliesRequest.Validate if the designated constraints aren't met.
type ListIssueRepliesRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListIssueRepliesRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListIssueRepliesRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListIssueRepliesRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListIssueRepliesRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListIssueRepliesRequestValidationError) ErrorName() string {
	return "ListIssueRepliesRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListIssueRepliesRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListIssueRepliesRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListIssueRepliesRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListIssueRepliesRequestValidationError{}

// Validate checks the field values on ListIssueRepliesResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListIssueRepliesResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListIssueRepliesResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListIssueRepliesResponseMultiError, or nil if none found.
func (m *ListIssueRepliesResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListIssueRepliesResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetReplies() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListIssueRepliesResponseValidationError{
						field:  fmt.Sprintf("Replies[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListIssueRepliesResponseValidationError{
						field:  fmt.Sprintf("Replies[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListIssueRepliesResponseValidationError{
					field:  fmt.Sprintf("Replies[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListIssueRepliesResponseMultiError(errors)
	}

	return nil
}

// ListIssueRepliesResponseMultiError is an error wrapping multiple validation
// errors returned by ListIssueRepliesResponse.ValidateAll() if the designated
// constraints aren't met.
type ListIssueRepliesResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListIssueRepliesResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListIssueRepliesResponseMultiError) AllErrors() []error { return m }

// ListIssueRepliesResponseValidationError is the validation error returned by
// ListIssueRepliesResponse.Validate if the designated constraints aren't met.
type ListIssueRepliesResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListIssueRepliesResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListIssueRepliesResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListIssueRepliesResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListIssueRepliesResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListIssueRepliesResponseValidationError) ErrorName() string {
	return "ListIssueRepliesResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListIssueRepliesResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListIssueRepliesResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListIssueRepliesResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListIssueRepliesResponseValidationError{}

// Validate checks the field values on DeleteIssueReplyRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteIssueReplyRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteIssueReplyRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteIssueReplyRequestMultiError, or nil if none found.
func (m *DeleteIssueReplyRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteIssueReplyRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return DeleteIssueReplyRequestMultiError(errors)
	}

	return nil
}

// DeleteIssueReplyRequestMultiError is an error wrapping multiple validation
// errors returned by DeleteIssueReplyRequest.ValidateAll() if the designated
// constraints aren't met.
type DeleteIssueReplyRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteIssueReplyRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteIssueReplyRequestMultiError) AllErrors() []error { return m }

// DeleteIssueReplyRequestValidationError is the validation error returned by
// DeleteIssueReplyRequest.Validate if the designated constraints aren't met.
type DeleteIssueReplyRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteIssueReplyRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteIssueReplyRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteIssueReplyRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteIssueReplyRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteIssueReplyRequestValidationError) ErrorName() string {
	return "DeleteIssueReplyRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteIssueReplyRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteIssueReplyRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteIssueReplyRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteIssueReplyRequestValidationError{}

// Validate checks the field values on DeleteIssueReplyResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteIssueReplyResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteIssueReplyResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteIssueReplyResponseMultiError, or nil if none found.
func (m *DeleteIssueReplyResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteIssueReplyResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Success

	if len(errors) > 0 {
		return DeleteIssueReplyResponseMultiError(errors)
	}

	return nil
}

// DeleteIssueReplyResponseMultiError is an error wrapping multiple validation
// errors returned by DeleteIssueReplyResponse.ValidateAll() if the designated
// constraints aren't met.
type DeleteIssueReplyResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteIssueReplyResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteIssueReplyResponseMultiError) AllErrors() []error { return m }

// DeleteIssueReplyResponseValidationError is the validation error returned by
// DeleteIssueReplyResponse.Validate if the designated constraints aren't met.
type DeleteIssueReplyResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteIssueReplyResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteIssueReplyResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteIssueReplyResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteIssueReplyResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteIssueReplyResponseValidationError) ErrorName() string {
	return "DeleteIssueReplyResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteIssueReplyResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteIssueReplyResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteIssueReplyResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteIssueReplyResponseValidationError{}

// Validate checks the field values on UpdateIssueStatusRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateIssueStatusRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateIssueStatusRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateIssueStatusRequestMultiError, or nil if none found.
func (m *UpdateIssueStatusRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateIssueStatusRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Status

	if len(errors) > 0 {
		return UpdateIssueStatusRequestMultiError(errors)
	}

	return nil
}

// UpdateIssueStatusRequestMultiError is an error wrapping multiple validation
// errors returned by UpdateIssueStatusRequest.ValidateAll() if the designated
// constraints aren't met.
type UpdateIssueStatusRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateIssueStatusRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateIssueStatusRequestMultiError) AllErrors() []error { return m }

// UpdateIssueStatusRequestValidationError is the validation error returned by
// UpdateIssueStatusRequest.Validate if the designated constraints aren't met.
type UpdateIssueStatusRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateIssueStatusRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateIssueStatusRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateIssueStatusRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateIssueStatusRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateIssueStatusRequestValidationError) ErrorName() string {
	return "UpdateIssueStatusRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateIssueStatusRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateIssueStatusRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateIssueStatusRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateIssueStatusRequestValidationError{}

// Validate checks the field values on UpdateIssueStatusResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateIssueStatusResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateIssueStatusResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateIssueStatusResponseMultiError, or nil if none found.
func (m *UpdateIssueStatusResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateIssueStatusResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetIssue()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateIssueStatusResponseValidationError{
					field:  "Issue",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateIssueStatusResponseValidationError{
					field:  "Issue",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetIssue()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateIssueStatusResponseValidationError{
				field:  "Issue",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UpdateIssueStatusResponseMultiError(errors)
	}

	return nil
}

// UpdateIssueStatusResponseMultiError is an error wrapping multiple validation
// errors returned by UpdateIssueStatusResponse.ValidateAll() if the
// designated constraints aren't met.
type UpdateIssueStatusResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateIssueStatusResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateIssueStatusResponseMultiError) AllErrors() []error { return m }

// UpdateIssueStatusResponseValidationError is the validation error returned by
// UpdateIssueStatusResponse.Validate if the designated constraints aren't met.
type UpdateIssueStatusResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateIssueStatusResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateIssueStatusResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateIssueStatusResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateIssueStatusResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateIssueStatusResponseValidationError) ErrorName() string {
	return "UpdateIssueStatusResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateIssueStatusResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateIssueStatusResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateIssueStatusResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateIssueStatusResponseValidationError{}

// Validate checks the field values on ListIssueConfigRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListIssueConfigRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListIssueConfigRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListIssueConfigRequestMultiError, or nil if none found.
func (m *ListIssueConfigRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListIssueConfigRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return ListIssueConfigRequestMultiError(errors)
	}

	return nil
}

// ListIssueConfigRequestMultiError is an error wrapping multiple validation
// errors returned by ListIssueConfigRequest.ValidateAll() if the designated
// constraints aren't met.
type ListIssueConfigRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListIssueConfigRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListIssueConfigRequestMultiError) AllErrors() []error { return m }

// ListIssueConfigRequestValidationError is the validation error returned by
// ListIssueConfigRequest.Validate if the designated constraints aren't met.
type ListIssueConfigRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListIssueConfigRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListIssueConfigRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListIssueConfigRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListIssueConfigRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListIssueConfigRequestValidationError) ErrorName() string {
	return "ListIssueConfigRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListIssueConfigRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListIssueConfigRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListIssueConfigRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListIssueConfigRequestValidationError{}

// Validate checks the field values on ListIssueConfigResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListIssueConfigResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListIssueConfigResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListIssueConfigResponseMultiError, or nil if none found.
func (m *ListIssueConfigResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListIssueConfigResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return ListIssueConfigResponseMultiError(errors)
	}

	return nil
}

// ListIssueConfigResponseMultiError is an error wrapping multiple validation
// errors returned by ListIssueConfigResponse.ValidateAll() if the designated
// constraints aren't met.
type ListIssueConfigResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListIssueConfigResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListIssueConfigResponseMultiError) AllErrors() []error { return m }

// ListIssueConfigResponseValidationError is the validation error returned by
// ListIssueConfigResponse.Validate if the designated constraints aren't met.
type ListIssueConfigResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListIssueConfigResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListIssueConfigResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListIssueConfigResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListIssueConfigResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListIssueConfigResponseValidationError) ErrorName() string {
	return "ListIssueConfigResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListIssueConfigResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListIssueConfigResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListIssueConfigResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListIssueConfigResponseValidationError{}
