// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: proto/helpdesk/v1/issues.proto

package helpdesk_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Issue represents a helpdesk issue
type Issue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     int32                  `protobuf:"varint,11,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Entity        string                 `protobuf:"bytes,12,opt,name=entity,proto3" json:"entity,omitempty"`
	EntityId      string                 `protobuf:"bytes,4,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"` // ID of the entity
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Status        int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"` // 1=open, 2=in_progress, 3=resolved, 4=closed
	CreatedAt     int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	IssueType     string                 `protobuf:"bytes,13,opt,name=issue_type,json=issueType,proto3" json:"issue_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Issue) Reset() {
	*x = Issue{}
	mi := &file_proto_helpdesk_v1_issues_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Issue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Issue) ProtoMessage() {}

func (x *Issue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helpdesk_v1_issues_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Issue.ProtoReflect.Descriptor instead.
func (*Issue) Descriptor() ([]byte, []int) {
	return file_proto_helpdesk_v1_issues_proto_rawDescGZIP(), []int{0}
}

func (x *Issue) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Issue) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Issue) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *Issue) GetEntity() string {
	if x != nil {
		return x.Entity
	}
	return ""
}

func (x *Issue) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *Issue) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Issue) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Issue) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Issue) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Issue) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Issue) GetIssueType() string {
	if x != nil {
		return x.IssueType
	}
	return ""
}

// IssueReply represents a reply in an issue conversation
type IssueReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IssueId       string                 `protobuf:"bytes,2,opt,name=issue_id,json=issueId,proto3" json:"issue_id,omitempty"`
	UserId        int32                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"` // "user" | "admin"
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	IsDeleted     bool                   `protobuf:"varint,6,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueReply) Reset() {
	*x = IssueReply{}
	mi := &file_proto_helpdesk_v1_issues_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueReply) ProtoMessage() {}

func (x *IssueReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helpdesk_v1_issues_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueReply.ProtoReflect.Descriptor instead.
func (*IssueReply) Descriptor() ([]byte, []int) {
	return file_proto_helpdesk_v1_issues_proto_rawDescGZIP(), []int{1}
}

func (x *IssueReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *IssueReply) GetIssueId() string {
	if x != nil {
		return x.IssueId
	}
	return ""
}

func (x *IssueReply) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *IssueReply) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *IssueReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *IssueReply) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

func (x *IssueReply) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type CreateIssueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int32                  `protobuf:"varint,11,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Entity        string                 `protobuf:"bytes,12,opt,name=entity,proto3" json:"entity,omitempty"`
	EntityId      string                 `protobuf:"bytes,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	IssueType     string                 `protobuf:"bytes,13,opt,name=issue_type,json=issueType,proto3" json:"issue_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateIssueRequest) Reset() {
	*x = CreateIssueRequest{}
	mi := &file_proto_helpdesk_v1_issues_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIssueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIssueRequest) ProtoMessage() {}

func (x *CreateIssueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helpdesk_v1_issues_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIssueRequest.ProtoReflect.Descriptor instead.
func (*CreateIssueRequest) Descriptor() ([]byte, []int) {
	return file_proto_helpdesk_v1_issues_proto_rawDescGZIP(), []int{2}
}

func (x *CreateIssueRequest) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CreateIssueRequest) GetEntity() string {
	if x != nil {
		return x.Entity
	}
	return ""
}

func (x *CreateIssueRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *CreateIssueRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateIssueRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateIssueRequest) GetIssueType() string {
	if x != nil {
		return x.IssueType
	}
	return ""
}

type CreateIssueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Issue         *Issue                 `protobuf:"bytes,1,opt,name=issue,proto3" json:"issue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateIssueResponse) Reset() {
	*x = CreateIssueResponse{}
	mi := &file_proto_helpdesk_v1_issues_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIssueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIssueResponse) ProtoMessage() {}

func (x *CreateIssueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helpdesk_v1_issues_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIssueResponse.ProtoReflect.Descriptor instead.
func (*CreateIssueResponse) Descriptor() ([]byte, []int) {
	return file_proto_helpdesk_v1_issues_proto_rawDescGZIP(), []int{3}
}

func (x *CreateIssueResponse) GetIssue() *Issue {
	if x != nil {
		return x.Issue
	}
	return nil
}

type GetIssueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIssueRequest) Reset() {
	*x = GetIssueRequest{}
	mi := &file_proto_helpdesk_v1_issues_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIssueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIssueRequest) ProtoMessage() {}

func (x *GetIssueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helpdesk_v1_issues_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIssueRequest.ProtoReflect.Descriptor instead.
func (*GetIssueRequest) Descriptor() ([]byte, []int) {
	return file_proto_helpdesk_v1_issues_proto_rawDescGZIP(), []int{4}
}

func (x *GetIssueRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetIssueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Issue         *Issue                 `protobuf:"bytes,1,opt,name=issue,proto3" json:"issue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIssueResponse) Reset() {
	*x = GetIssueResponse{}
	mi := &file_proto_helpdesk_v1_issues_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIssueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIssueResponse) ProtoMessage() {}

func (x *GetIssueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helpdesk_v1_issues_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIssueResponse.ProtoReflect.Descriptor instead.
func (*GetIssueResponse) Descriptor() ([]byte, []int) {
	return file_proto_helpdesk_v1_issues_proto_rawDescGZIP(), []int{5}
}

func (x *GetIssueResponse) GetIssue() *Issue {
	if x != nil {
		return x.Issue
	}
	return nil
}

type ListIssuesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Entity        string                 `protobuf:"bytes,12,opt,name=entity,proto3" json:"entity,omitempty"`
	EntityId      string                 `protobuf:"bytes,4,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	Page          int32                  `protobuf:"varint,6,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,7,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	IssueType     string                 `protobuf:"bytes,13,opt,name=issue_type,json=issueType,proto3" json:"issue_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIssuesRequest) Reset() {
	*x = ListIssuesRequest{}
	mi := &file_proto_helpdesk_v1_issues_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIssuesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIssuesRequest) ProtoMessage() {}

func (x *ListIssuesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helpdesk_v1_issues_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIssuesRequest.ProtoReflect.Descriptor instead.
func (*ListIssuesRequest) Descriptor() ([]byte, []int) {
	return file_proto_helpdesk_v1_issues_proto_rawDescGZIP(), []int{6}
}

func (x *ListIssuesRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ListIssuesRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListIssuesRequest) GetEntity() string {
	if x != nil {
		return x.Entity
	}
	return ""
}

func (x *ListIssuesRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *ListIssuesRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ListIssuesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListIssuesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListIssuesRequest) GetIssueType() string {
	if x != nil {
		return x.IssueType
	}
	return ""
}

type ListIssuesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Issues        []*Issue               `protobuf:"bytes,1,rep,name=issues,proto3" json:"issues,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIssuesResponse) Reset() {
	*x = ListIssuesResponse{}
	mi := &file_proto_helpdesk_v1_issues_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIssuesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIssuesResponse) ProtoMessage() {}

func (x *ListIssuesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helpdesk_v1_issues_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIssuesResponse.ProtoReflect.Descriptor instead.
func (*ListIssuesResponse) Descriptor() ([]byte, []int) {
	return file_proto_helpdesk_v1_issues_proto_rawDescGZIP(), []int{7}
}

func (x *ListIssuesResponse) GetIssues() []*Issue {
	if x != nil {
		return x.Issues
	}
	return nil
}

type UpdateIssueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	IssueType     string                 `protobuf:"bytes,13,opt,name=issue_type,json=issueType,proto3" json:"issue_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateIssueRequest) Reset() {
	*x = UpdateIssueRequest{}
	mi := &file_proto_helpdesk_v1_issues_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateIssueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateIssueRequest) ProtoMessage() {}

func (x *UpdateIssueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helpdesk_v1_issues_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateIssueRequest.ProtoReflect.Descriptor instead.
func (*UpdateIssueRequest) Descriptor() ([]byte, []int) {
	return file_proto_helpdesk_v1_issues_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateIssueRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateIssueRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateIssueRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateIssueRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdateIssueRequest) GetIssueType() string {
	if x != nil {
		return x.IssueType
	}
	return ""
}

type UpdateIssueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Issue         *Issue                 `protobuf:"bytes,1,opt,name=issue,proto3" json:"issue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateIssueResponse) Reset() {
	*x = UpdateIssueResponse{}
	mi := &file_proto_helpdesk_v1_issues_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateIssueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateIssueResponse) ProtoMessage() {}

func (x *UpdateIssueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helpdesk_v1_issues_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateIssueResponse.ProtoReflect.Descriptor instead.
func (*UpdateIssueResponse) Descriptor() ([]byte, []int) {
	return file_proto_helpdesk_v1_issues_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateIssueResponse) GetIssue() *Issue {
	if x != nil {
		return x.Issue
	}
	return nil
}

type DeleteIssueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteIssueRequest) Reset() {
	*x = DeleteIssueRequest{}
	mi := &file_proto_helpdesk_v1_issues_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteIssueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteIssueRequest) ProtoMessage() {}

func (x *DeleteIssueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helpdesk_v1_issues_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteIssueRequest.ProtoReflect.Descriptor instead.
func (*DeleteIssueRequest) Descriptor() ([]byte, []int) {
	return file_proto_helpdesk_v1_issues_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteIssueRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteIssueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteIssueResponse) Reset() {
	*x = DeleteIssueResponse{}
	mi := &file_proto_helpdesk_v1_issues_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteIssueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteIssueResponse) ProtoMessage() {}

func (x *DeleteIssueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helpdesk_v1_issues_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteIssueResponse.ProtoReflect.Descriptor instead.
func (*DeleteIssueResponse) Descriptor() ([]byte, []int) {
	return file_proto_helpdesk_v1_issues_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteIssueResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CreateIssueReplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IssueId       string                 `protobuf:"bytes,1,opt,name=issue_id,json=issueId,proto3" json:"issue_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateIssueReplyRequest) Reset() {
	*x = CreateIssueReplyRequest{}
	mi := &file_proto_helpdesk_v1_issues_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIssueReplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIssueReplyRequest) ProtoMessage() {}

func (x *CreateIssueReplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helpdesk_v1_issues_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIssueReplyRequest.ProtoReflect.Descriptor instead.
func (*CreateIssueReplyRequest) Descriptor() ([]byte, []int) {
	return file_proto_helpdesk_v1_issues_proto_rawDescGZIP(), []int{12}
}

func (x *CreateIssueReplyRequest) GetIssueId() string {
	if x != nil {
		return x.IssueId
	}
	return ""
}

func (x *CreateIssueReplyRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateIssueReplyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reply         *IssueReply            `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateIssueReplyResponse) Reset() {
	*x = CreateIssueReplyResponse{}
	mi := &file_proto_helpdesk_v1_issues_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIssueReplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIssueReplyResponse) ProtoMessage() {}

func (x *CreateIssueReplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helpdesk_v1_issues_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIssueReplyResponse.ProtoReflect.Descriptor instead.
func (*CreateIssueReplyResponse) Descriptor() ([]byte, []int) {
	return file_proto_helpdesk_v1_issues_proto_rawDescGZIP(), []int{13}
}

func (x *CreateIssueReplyResponse) GetReply() *IssueReply {
	if x != nil {
		return x.Reply
	}
	return nil
}

type ListIssueRepliesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IssueId       string                 `protobuf:"bytes,1,opt,name=issue_id,json=issueId,proto3" json:"issue_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIssueRepliesRequest) Reset() {
	*x = ListIssueRepliesRequest{}
	mi := &file_proto_helpdesk_v1_issues_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIssueRepliesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIssueRepliesRequest) ProtoMessage() {}

func (x *ListIssueRepliesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helpdesk_v1_issues_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIssueRepliesRequest.ProtoReflect.Descriptor instead.
func (*ListIssueRepliesRequest) Descriptor() ([]byte, []int) {
	return file_proto_helpdesk_v1_issues_proto_rawDescGZIP(), []int{14}
}

func (x *ListIssueRepliesRequest) GetIssueId() string {
	if x != nil {
		return x.IssueId
	}
	return ""
}

func (x *ListIssueRepliesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListIssueRepliesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListIssueRepliesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Replies       []*IssueReply          `protobuf:"bytes,1,rep,name=replies,proto3" json:"replies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIssueRepliesResponse) Reset() {
	*x = ListIssueRepliesResponse{}
	mi := &file_proto_helpdesk_v1_issues_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIssueRepliesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIssueRepliesResponse) ProtoMessage() {}

func (x *ListIssueRepliesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helpdesk_v1_issues_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIssueRepliesResponse.ProtoReflect.Descriptor instead.
func (*ListIssueRepliesResponse) Descriptor() ([]byte, []int) {
	return file_proto_helpdesk_v1_issues_proto_rawDescGZIP(), []int{15}
}

func (x *ListIssueRepliesResponse) GetReplies() []*IssueReply {
	if x != nil {
		return x.Replies
	}
	return nil
}

type DeleteIssueReplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteIssueReplyRequest) Reset() {
	*x = DeleteIssueReplyRequest{}
	mi := &file_proto_helpdesk_v1_issues_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteIssueReplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteIssueReplyRequest) ProtoMessage() {}

func (x *DeleteIssueReplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helpdesk_v1_issues_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteIssueReplyRequest.ProtoReflect.Descriptor instead.
func (*DeleteIssueReplyRequest) Descriptor() ([]byte, []int) {
	return file_proto_helpdesk_v1_issues_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteIssueReplyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteIssueReplyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteIssueReplyResponse) Reset() {
	*x = DeleteIssueReplyResponse{}
	mi := &file_proto_helpdesk_v1_issues_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteIssueReplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteIssueReplyResponse) ProtoMessage() {}

func (x *DeleteIssueReplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helpdesk_v1_issues_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteIssueReplyResponse.ProtoReflect.Descriptor instead.
func (*DeleteIssueReplyResponse) Descriptor() ([]byte, []int) {
	return file_proto_helpdesk_v1_issues_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteIssueReplyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UpdateIssueStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateIssueStatusRequest) Reset() {
	*x = UpdateIssueStatusRequest{}
	mi := &file_proto_helpdesk_v1_issues_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateIssueStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateIssueStatusRequest) ProtoMessage() {}

func (x *UpdateIssueStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helpdesk_v1_issues_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateIssueStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateIssueStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_helpdesk_v1_issues_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateIssueStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateIssueStatusRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type UpdateIssueStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Issue         *Issue                 `protobuf:"bytes,1,opt,name=issue,proto3" json:"issue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateIssueStatusResponse) Reset() {
	*x = UpdateIssueStatusResponse{}
	mi := &file_proto_helpdesk_v1_issues_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateIssueStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateIssueStatusResponse) ProtoMessage() {}

func (x *UpdateIssueStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helpdesk_v1_issues_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateIssueStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateIssueStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_helpdesk_v1_issues_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateIssueStatusResponse) GetIssue() *Issue {
	if x != nil {
		return x.Issue
	}
	return nil
}

type ListIssueConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIssueConfigRequest) Reset() {
	*x = ListIssueConfigRequest{}
	mi := &file_proto_helpdesk_v1_issues_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIssueConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIssueConfigRequest) ProtoMessage() {}

func (x *ListIssueConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helpdesk_v1_issues_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIssueConfigRequest.ProtoReflect.Descriptor instead.
func (*ListIssueConfigRequest) Descriptor() ([]byte, []int) {
	return file_proto_helpdesk_v1_issues_proto_rawDescGZIP(), []int{20}
}

type ListIssueConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entities      []string               `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	Types         []string               `protobuf:"bytes,2,rep,name=types,proto3" json:"types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIssueConfigResponse) Reset() {
	*x = ListIssueConfigResponse{}
	mi := &file_proto_helpdesk_v1_issues_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIssueConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIssueConfigResponse) ProtoMessage() {}

func (x *ListIssueConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helpdesk_v1_issues_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIssueConfigResponse.ProtoReflect.Descriptor instead.
func (*ListIssueConfigResponse) Descriptor() ([]byte, []int) {
	return file_proto_helpdesk_v1_issues_proto_rawDescGZIP(), []int{21}
}

func (x *ListIssueConfigResponse) GetEntities() []string {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *ListIssueConfigResponse) GetTypes() []string {
	if x != nil {
		return x.Types
	}
	return nil
}

var File_proto_helpdesk_v1_issues_proto protoreflect.FileDescriptor

const file_proto_helpdesk_v1_issues_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/helpdesk/v1/issues.proto\x12\x02v1\"\xb1\x02\n" +
	"\x05Issue\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\v \x01(\x05R\tproductId\x12\x16\n" +
	"\x06entity\x18\f \x01(\tR\x06entity\x12\x1b\n" +
	"\tentity_id\x18\x04 \x01(\tR\bentityId\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\x03R\tupdatedAt\x12\x1d\n" +
	"\n" +
	"issue_type\x18\r \x01(\tR\tissueType\"\xbc\x01\n" +
	"\n" +
	"IssueReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bissue_id\x18\x02 \x01(\tR\aissueId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x05R\x06userId\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\x06 \x01(\bR\tisDeleted\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\"\xbf\x01\n" +
	"\x12CreateIssueRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\v \x01(\x05R\tproductId\x12\x16\n" +
	"\x06entity\x18\f \x01(\tR\x06entity\x12\x1b\n" +
	"\tentity_id\x18\x02 \x01(\tR\bentityId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"issue_type\x18\r \x01(\tR\tissueType\"6\n" +
	"\x13CreateIssueResponse\x12\x1f\n" +
	"\x05issue\x18\x01 \x01(\v2\t.v1.IssueR\x05issue\"!\n" +
	"\x0fGetIssueRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"3\n" +
	"\x10GetIssueResponse\x12\x1f\n" +
	"\x05issue\x18\x01 \x01(\v2\t.v1.IssueR\x05issue\"\xd9\x01\n" +
	"\x11ListIssuesRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\x16\n" +
	"\x06entity\x18\f \x01(\tR\x06entity\x12\x1b\n" +
	"\tentity_id\x18\x04 \x01(\tR\bentityId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12\x12\n" +
	"\x04page\x18\x06 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\a \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"issue_type\x18\r \x01(\tR\tissueType\"7\n" +
	"\x12ListIssuesResponse\x12!\n" +
	"\x06issues\x18\x01 \x03(\v2\t.v1.IssueR\x06issues\"\x93\x01\n" +
	"\x12UpdateIssueRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"issue_type\x18\r \x01(\tR\tissueType\"6\n" +
	"\x13UpdateIssueResponse\x12\x1f\n" +
	"\x05issue\x18\x01 \x01(\v2\t.v1.IssueR\x05issue\"$\n" +
	"\x12DeleteIssueRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"/\n" +
	"\x13DeleteIssueResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"N\n" +
	"\x17CreateIssueReplyRequest\x12\x19\n" +
	"\bissue_id\x18\x01 \x01(\tR\aissueId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"@\n" +
	"\x18CreateIssueReplyResponse\x12$\n" +
	"\x05reply\x18\x01 \x01(\v2\x0e.v1.IssueReplyR\x05reply\"e\n" +
	"\x17ListIssueRepliesRequest\x12\x19\n" +
	"\bissue_id\x18\x01 \x01(\tR\aissueId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"D\n" +
	"\x18ListIssueRepliesResponse\x12(\n" +
	"\areplies\x18\x01 \x03(\v2\x0e.v1.IssueReplyR\areplies\")\n" +
	"\x17DeleteIssueReplyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"4\n" +
	"\x18DeleteIssueReplyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"B\n" +
	"\x18UpdateIssueStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\"<\n" +
	"\x19UpdateIssueStatusResponse\x12\x1f\n" +
	"\x05issue\x18\x01 \x01(\v2\t.v1.IssueR\x05issue\"\x18\n" +
	"\x16ListIssueConfigRequest\"K\n" +
	"\x17ListIssueConfigResponse\x12\x1a\n" +
	"\bentities\x18\x01 \x03(\tR\bentities\x12\x14\n" +
	"\x05types\x18\x02 \x03(\tR\x05typesB\x0fZ\r./helpdesk_v1b\x06proto3"

var (
	file_proto_helpdesk_v1_issues_proto_rawDescOnce sync.Once
	file_proto_helpdesk_v1_issues_proto_rawDescData []byte
)

func file_proto_helpdesk_v1_issues_proto_rawDescGZIP() []byte {
	file_proto_helpdesk_v1_issues_proto_rawDescOnce.Do(func() {
		file_proto_helpdesk_v1_issues_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_helpdesk_v1_issues_proto_rawDesc), len(file_proto_helpdesk_v1_issues_proto_rawDesc)))
	})
	return file_proto_helpdesk_v1_issues_proto_rawDescData
}

var file_proto_helpdesk_v1_issues_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_proto_helpdesk_v1_issues_proto_goTypes = []any{
	(*Issue)(nil),                     // 0: v1.Issue
	(*IssueReply)(nil),                // 1: v1.IssueReply
	(*CreateIssueRequest)(nil),        // 2: v1.CreateIssueRequest
	(*CreateIssueResponse)(nil),       // 3: v1.CreateIssueResponse
	(*GetIssueRequest)(nil),           // 4: v1.GetIssueRequest
	(*GetIssueResponse)(nil),          // 5: v1.GetIssueResponse
	(*ListIssuesRequest)(nil),         // 6: v1.ListIssuesRequest
	(*ListIssuesResponse)(nil),        // 7: v1.ListIssuesResponse
	(*UpdateIssueRequest)(nil),        // 8: v1.UpdateIssueRequest
	(*UpdateIssueResponse)(nil),       // 9: v1.UpdateIssueResponse
	(*DeleteIssueRequest)(nil),        // 10: v1.DeleteIssueRequest
	(*DeleteIssueResponse)(nil),       // 11: v1.DeleteIssueResponse
	(*CreateIssueReplyRequest)(nil),   // 12: v1.CreateIssueReplyRequest
	(*CreateIssueReplyResponse)(nil),  // 13: v1.CreateIssueReplyResponse
	(*ListIssueRepliesRequest)(nil),   // 14: v1.ListIssueRepliesRequest
	(*ListIssueRepliesResponse)(nil),  // 15: v1.ListIssueRepliesResponse
	(*DeleteIssueReplyRequest)(nil),   // 16: v1.DeleteIssueReplyRequest
	(*DeleteIssueReplyResponse)(nil),  // 17: v1.DeleteIssueReplyResponse
	(*UpdateIssueStatusRequest)(nil),  // 18: v1.UpdateIssueStatusRequest
	(*UpdateIssueStatusResponse)(nil), // 19: v1.UpdateIssueStatusResponse
	(*ListIssueConfigRequest)(nil),    // 20: v1.ListIssueConfigRequest
	(*ListIssueConfigResponse)(nil),   // 21: v1.ListIssueConfigResponse
}
var file_proto_helpdesk_v1_issues_proto_depIdxs = []int32{
	0, // 0: v1.CreateIssueResponse.issue:type_name -> v1.Issue
	0, // 1: v1.GetIssueResponse.issue:type_name -> v1.Issue
	0, // 2: v1.ListIssuesResponse.issues:type_name -> v1.Issue
	0, // 3: v1.UpdateIssueResponse.issue:type_name -> v1.Issue
	1, // 4: v1.CreateIssueReplyResponse.reply:type_name -> v1.IssueReply
	1, // 5: v1.ListIssueRepliesResponse.replies:type_name -> v1.IssueReply
	0, // 6: v1.UpdateIssueStatusResponse.issue:type_name -> v1.Issue
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_proto_helpdesk_v1_issues_proto_init() }
func file_proto_helpdesk_v1_issues_proto_init() {
	if File_proto_helpdesk_v1_issues_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_helpdesk_v1_issues_proto_rawDesc), len(file_proto_helpdesk_v1_issues_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_helpdesk_v1_issues_proto_goTypes,
		DependencyIndexes: file_proto_helpdesk_v1_issues_proto_depIdxs,
		MessageInfos:      file_proto_helpdesk_v1_issues_proto_msgTypes,
	}.Build()
	File_proto_helpdesk_v1_issues_proto = out.File
	file_proto_helpdesk_v1_issues_proto_goTypes = nil
	file_proto_helpdesk_v1_issues_proto_depIdxs = nil
}
