// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: proto/common/ping.proto

package helpdesk_v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on HDPingRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *HDPingRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on HDPingRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in HDPingRequestMultiError, or
// nil if none found.
func (m *HDPingRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *HDPingRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetMessage()); l < 1 || l > 100 {
		err := HDPingRequestValidationError{
			field:  "Message",
			reason: "value length must be between 1 and 100 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_HDPingRequest_Message_Pattern.MatchString(m.GetMessage()) {
		err := HDPingRequestValidationError{
			field:  "Message",
			reason: "value does not match regex pattern \"^[a-zA-Z0-9\\\\s\\\\-_.,!?]+$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return HDPingRequestMultiError(errors)
	}

	return nil
}

// HDPingRequestMultiError is an error wrapping multiple validation errors
// returned by HDPingRequest.ValidateAll() if the designated constraints
// aren't met.
type HDPingRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HDPingRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HDPingRequestMultiError) AllErrors() []error { return m }

// HDPingRequestValidationError is the validation error returned by
// HDPingRequest.Validate if the designated constraints aren't met.
type HDPingRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HDPingRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HDPingRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HDPingRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HDPingRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HDPingRequestValidationError) ErrorName() string { return "HDPingRequestValidationError" }

// Error satisfies the builtin error interface
func (e HDPingRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHDPingRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HDPingRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HDPingRequestValidationError{}

var _HDPingRequest_Message_Pattern = regexp.MustCompile("^[a-zA-Z0-9\\s\\-_.,!?]+$")

// Validate checks the field values on HDPingResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *HDPingResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on HDPingResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in HDPingResponseMultiError,
// or nil if none found.
func (m *HDPingResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *HDPingResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Message

	if len(errors) > 0 {
		return HDPingResponseMultiError(errors)
	}

	return nil
}

// HDPingResponseMultiError is an error wrapping multiple validation errors
// returned by HDPingResponse.ValidateAll() if the designated constraints
// aren't met.
type HDPingResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HDPingResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HDPingResponseMultiError) AllErrors() []error { return m }

// HDPingResponseValidationError is the validation error returned by
// HDPingResponse.Validate if the designated constraints aren't met.
type HDPingResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HDPingResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HDPingResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HDPingResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HDPingResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HDPingResponseValidationError) ErrorName() string { return "HDPingResponseValidationError" }

// Error satisfies the builtin error interface
func (e HDPingResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHDPingResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HDPingResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HDPingResponseValidationError{}
