// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: proto/helpdesk/v1/ratings.proto

package helpdesk_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Rating represents a user's rating of an entity
type Rating struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`                             // entity type: "product", "order", "service", etc.
	EntityId      string                 `protobuf:"bytes,4,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`     // ID of the rated entity
	Rating        float32                `protobuf:"fixed32,5,opt,name=rating,proto3" json:"rating,omitempty"`                       // numeric score (e.g. 1.0, 2.5, 5.0)
	Comment       string                 `protobuf:"bytes,6,opt,name=comment,proto3" json:"comment,omitempty"`                       // optional free-text feedback
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Unix epoch milliseconds
	UpdatedAt     int64                  `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // Unix epoch milliseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rating) Reset() {
	*x = Rating{}
	mi := &file_proto_helpdesk_v1_ratings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rating) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rating) ProtoMessage() {}

func (x *Rating) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helpdesk_v1_ratings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rating.ProtoReflect.Descriptor instead.
func (*Rating) Descriptor() ([]byte, []int) {
	return file_proto_helpdesk_v1_ratings_proto_rawDescGZIP(), []int{0}
}

func (x *Rating) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Rating) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Rating) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Rating) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *Rating) GetRating() float32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Rating) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *Rating) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Rating) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// RatingReply represents a response to a rating (from admin/owner)
type RatingReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RatingId      string                 `protobuf:"bytes,2,opt,name=rating_id,json=ratingId,proto3" json:"rating_id,omitempty"`
	UserId        int32                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"` // "user" | "admin"
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	IsDeleted     bool                   `protobuf:"varint,6,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RatingReply) Reset() {
	*x = RatingReply{}
	mi := &file_proto_helpdesk_v1_ratings_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RatingReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RatingReply) ProtoMessage() {}

func (x *RatingReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helpdesk_v1_ratings_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RatingReply.ProtoReflect.Descriptor instead.
func (*RatingReply) Descriptor() ([]byte, []int) {
	return file_proto_helpdesk_v1_ratings_proto_rawDescGZIP(), []int{1}
}

func (x *RatingReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RatingReply) GetRatingId() string {
	if x != nil {
		return x.RatingId
	}
	return ""
}

func (x *RatingReply) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RatingReply) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *RatingReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RatingReply) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

func (x *RatingReply) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type CreateRatingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	EntityId      string                 `protobuf:"bytes,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Rating        float32                `protobuf:"fixed32,3,opt,name=rating,proto3" json:"rating,omitempty"`
	Comment       string                 `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRatingRequest) Reset() {
	*x = CreateRatingRequest{}
	mi := &file_proto_helpdesk_v1_ratings_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRatingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRatingRequest) ProtoMessage() {}

func (x *CreateRatingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helpdesk_v1_ratings_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRatingRequest.ProtoReflect.Descriptor instead.
func (*CreateRatingRequest) Descriptor() ([]byte, []int) {
	return file_proto_helpdesk_v1_ratings_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRatingRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateRatingRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *CreateRatingRequest) GetRating() float32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *CreateRatingRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type CreateRatingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rating        *Rating                `protobuf:"bytes,1,opt,name=rating,proto3" json:"rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRatingResponse) Reset() {
	*x = CreateRatingResponse{}
	mi := &file_proto_helpdesk_v1_ratings_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRatingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRatingResponse) ProtoMessage() {}

func (x *CreateRatingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helpdesk_v1_ratings_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRatingResponse.ProtoReflect.Descriptor instead.
func (*CreateRatingResponse) Descriptor() ([]byte, []int) {
	return file_proto_helpdesk_v1_ratings_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRatingResponse) GetRating() *Rating {
	if x != nil {
		return x.Rating
	}
	return nil
}

type GetRatingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRatingRequest) Reset() {
	*x = GetRatingRequest{}
	mi := &file_proto_helpdesk_v1_ratings_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRatingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRatingRequest) ProtoMessage() {}

func (x *GetRatingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helpdesk_v1_ratings_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRatingRequest.ProtoReflect.Descriptor instead.
func (*GetRatingRequest) Descriptor() ([]byte, []int) {
	return file_proto_helpdesk_v1_ratings_proto_rawDescGZIP(), []int{4}
}

func (x *GetRatingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetRatingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rating        *Rating                `protobuf:"bytes,1,opt,name=rating,proto3" json:"rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRatingResponse) Reset() {
	*x = GetRatingResponse{}
	mi := &file_proto_helpdesk_v1_ratings_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRatingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRatingResponse) ProtoMessage() {}

func (x *GetRatingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helpdesk_v1_ratings_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRatingResponse.ProtoReflect.Descriptor instead.
func (*GetRatingResponse) Descriptor() ([]byte, []int) {
	return file_proto_helpdesk_v1_ratings_proto_rawDescGZIP(), []int{5}
}

func (x *GetRatingResponse) GetRating() *Rating {
	if x != nil {
		return x.Rating
	}
	return nil
}

type ListRatingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	EntityId      string                 `protobuf:"bytes,4,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Page          int32                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRatingsRequest) Reset() {
	*x = ListRatingsRequest{}
	mi := &file_proto_helpdesk_v1_ratings_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRatingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRatingsRequest) ProtoMessage() {}

func (x *ListRatingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helpdesk_v1_ratings_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRatingsRequest.ProtoReflect.Descriptor instead.
func (*ListRatingsRequest) Descriptor() ([]byte, []int) {
	return file_proto_helpdesk_v1_ratings_proto_rawDescGZIP(), []int{6}
}

func (x *ListRatingsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ListRatingsRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListRatingsRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ListRatingsRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *ListRatingsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListRatingsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListRatingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ratings       []*Rating              `protobuf:"bytes,1,rep,name=ratings,proto3" json:"ratings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRatingsResponse) Reset() {
	*x = ListRatingsResponse{}
	mi := &file_proto_helpdesk_v1_ratings_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRatingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRatingsResponse) ProtoMessage() {}

func (x *ListRatingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helpdesk_v1_ratings_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRatingsResponse.ProtoReflect.Descriptor instead.
func (*ListRatingsResponse) Descriptor() ([]byte, []int) {
	return file_proto_helpdesk_v1_ratings_proto_rawDescGZIP(), []int{7}
}

func (x *ListRatingsResponse) GetRatings() []*Rating {
	if x != nil {
		return x.Ratings
	}
	return nil
}

type UpdateRatingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Rating        float32                `protobuf:"fixed32,2,opt,name=rating,proto3" json:"rating,omitempty"`
	Comment       string                 `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRatingRequest) Reset() {
	*x = UpdateRatingRequest{}
	mi := &file_proto_helpdesk_v1_ratings_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRatingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRatingRequest) ProtoMessage() {}

func (x *UpdateRatingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helpdesk_v1_ratings_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRatingRequest.ProtoReflect.Descriptor instead.
func (*UpdateRatingRequest) Descriptor() ([]byte, []int) {
	return file_proto_helpdesk_v1_ratings_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateRatingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateRatingRequest) GetRating() float32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *UpdateRatingRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type UpdateRatingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rating        *Rating                `protobuf:"bytes,1,opt,name=rating,proto3" json:"rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRatingResponse) Reset() {
	*x = UpdateRatingResponse{}
	mi := &file_proto_helpdesk_v1_ratings_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRatingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRatingResponse) ProtoMessage() {}

func (x *UpdateRatingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helpdesk_v1_ratings_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRatingResponse.ProtoReflect.Descriptor instead.
func (*UpdateRatingResponse) Descriptor() ([]byte, []int) {
	return file_proto_helpdesk_v1_ratings_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateRatingResponse) GetRating() *Rating {
	if x != nil {
		return x.Rating
	}
	return nil
}

type DeleteRatingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRatingRequest) Reset() {
	*x = DeleteRatingRequest{}
	mi := &file_proto_helpdesk_v1_ratings_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRatingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRatingRequest) ProtoMessage() {}

func (x *DeleteRatingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helpdesk_v1_ratings_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRatingRequest.ProtoReflect.Descriptor instead.
func (*DeleteRatingRequest) Descriptor() ([]byte, []int) {
	return file_proto_helpdesk_v1_ratings_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteRatingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteRatingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRatingResponse) Reset() {
	*x = DeleteRatingResponse{}
	mi := &file_proto_helpdesk_v1_ratings_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRatingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRatingResponse) ProtoMessage() {}

func (x *DeleteRatingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helpdesk_v1_ratings_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRatingResponse.ProtoReflect.Descriptor instead.
func (*DeleteRatingResponse) Descriptor() ([]byte, []int) {
	return file_proto_helpdesk_v1_ratings_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteRatingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CreateRatingReplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RatingId      string                 `protobuf:"bytes,1,opt,name=rating_id,json=ratingId,proto3" json:"rating_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRatingReplyRequest) Reset() {
	*x = CreateRatingReplyRequest{}
	mi := &file_proto_helpdesk_v1_ratings_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRatingReplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRatingReplyRequest) ProtoMessage() {}

func (x *CreateRatingReplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helpdesk_v1_ratings_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRatingReplyRequest.ProtoReflect.Descriptor instead.
func (*CreateRatingReplyRequest) Descriptor() ([]byte, []int) {
	return file_proto_helpdesk_v1_ratings_proto_rawDescGZIP(), []int{12}
}

func (x *CreateRatingReplyRequest) GetRatingId() string {
	if x != nil {
		return x.RatingId
	}
	return ""
}

func (x *CreateRatingReplyRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateRatingReplyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reply         *RatingReply           `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRatingReplyResponse) Reset() {
	*x = CreateRatingReplyResponse{}
	mi := &file_proto_helpdesk_v1_ratings_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRatingReplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRatingReplyResponse) ProtoMessage() {}

func (x *CreateRatingReplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helpdesk_v1_ratings_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRatingReplyResponse.ProtoReflect.Descriptor instead.
func (*CreateRatingReplyResponse) Descriptor() ([]byte, []int) {
	return file_proto_helpdesk_v1_ratings_proto_rawDescGZIP(), []int{13}
}

func (x *CreateRatingReplyResponse) GetReply() *RatingReply {
	if x != nil {
		return x.Reply
	}
	return nil
}

type ListRatingRepliesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RatingId      string                 `protobuf:"bytes,1,opt,name=rating_id,json=ratingId,proto3" json:"rating_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRatingRepliesRequest) Reset() {
	*x = ListRatingRepliesRequest{}
	mi := &file_proto_helpdesk_v1_ratings_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRatingRepliesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRatingRepliesRequest) ProtoMessage() {}

func (x *ListRatingRepliesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helpdesk_v1_ratings_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRatingRepliesRequest.ProtoReflect.Descriptor instead.
func (*ListRatingRepliesRequest) Descriptor() ([]byte, []int) {
	return file_proto_helpdesk_v1_ratings_proto_rawDescGZIP(), []int{14}
}

func (x *ListRatingRepliesRequest) GetRatingId() string {
	if x != nil {
		return x.RatingId
	}
	return ""
}

func (x *ListRatingRepliesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListRatingRepliesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListRatingRepliesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Replies       []*RatingReply         `protobuf:"bytes,1,rep,name=replies,proto3" json:"replies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRatingRepliesResponse) Reset() {
	*x = ListRatingRepliesResponse{}
	mi := &file_proto_helpdesk_v1_ratings_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRatingRepliesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRatingRepliesResponse) ProtoMessage() {}

func (x *ListRatingRepliesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helpdesk_v1_ratings_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRatingRepliesResponse.ProtoReflect.Descriptor instead.
func (*ListRatingRepliesResponse) Descriptor() ([]byte, []int) {
	return file_proto_helpdesk_v1_ratings_proto_rawDescGZIP(), []int{15}
}

func (x *ListRatingRepliesResponse) GetReplies() []*RatingReply {
	if x != nil {
		return x.Replies
	}
	return nil
}

type DeleteRatingReplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRatingReplyRequest) Reset() {
	*x = DeleteRatingReplyRequest{}
	mi := &file_proto_helpdesk_v1_ratings_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRatingReplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRatingReplyRequest) ProtoMessage() {}

func (x *DeleteRatingReplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helpdesk_v1_ratings_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRatingReplyRequest.ProtoReflect.Descriptor instead.
func (*DeleteRatingReplyRequest) Descriptor() ([]byte, []int) {
	return file_proto_helpdesk_v1_ratings_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteRatingReplyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteRatingReplyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRatingReplyResponse) Reset() {
	*x = DeleteRatingReplyResponse{}
	mi := &file_proto_helpdesk_v1_ratings_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRatingReplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRatingReplyResponse) ProtoMessage() {}

func (x *DeleteRatingReplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helpdesk_v1_ratings_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRatingReplyResponse.ProtoReflect.Descriptor instead.
func (*DeleteRatingReplyResponse) Descriptor() ([]byte, []int) {
	return file_proto_helpdesk_v1_ratings_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteRatingReplyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetRatingsConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRatingsConfigRequest) Reset() {
	*x = GetRatingsConfigRequest{}
	mi := &file_proto_helpdesk_v1_ratings_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRatingsConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRatingsConfigRequest) ProtoMessage() {}

func (x *GetRatingsConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helpdesk_v1_ratings_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRatingsConfigRequest.ProtoReflect.Descriptor instead.
func (*GetRatingsConfigRequest) Descriptor() ([]byte, []int) {
	return file_proto_helpdesk_v1_ratings_proto_rawDescGZIP(), []int{18}
}

type GetRatingsConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Types         []string               `protobuf:"bytes,1,rep,name=types,proto3" json:"types,omitempty"`
	MaxRating     float32                `protobuf:"fixed32,2,opt,name=max_rating,json=maxRating,proto3" json:"max_rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRatingsConfigResponse) Reset() {
	*x = GetRatingsConfigResponse{}
	mi := &file_proto_helpdesk_v1_ratings_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRatingsConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRatingsConfigResponse) ProtoMessage() {}

func (x *GetRatingsConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helpdesk_v1_ratings_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRatingsConfigResponse.ProtoReflect.Descriptor instead.
func (*GetRatingsConfigResponse) Descriptor() ([]byte, []int) {
	return file_proto_helpdesk_v1_ratings_proto_rawDescGZIP(), []int{19}
}

func (x *GetRatingsConfigResponse) GetTypes() []string {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *GetRatingsConfigResponse) GetMaxRating() float32 {
	if x != nil {
		return x.MaxRating
	}
	return 0
}

var File_proto_helpdesk_v1_ratings_proto protoreflect.FileDescriptor

const file_proto_helpdesk_v1_ratings_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/helpdesk/v1/ratings.proto\x12\x02v1\"\xd2\x01\n" +
	"\x06Rating\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1b\n" +
	"\tentity_id\x18\x04 \x01(\tR\bentityId\x12\x16\n" +
	"\x06rating\x18\x05 \x01(\x02R\x06rating\x12\x18\n" +
	"\acomment\x18\x06 \x01(\tR\acomment\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\x03R\tupdatedAt\"\xbf\x01\n" +
	"\vRatingReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\trating_id\x18\x02 \x01(\tR\bratingId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x05R\x06userId\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\x06 \x01(\bR\tisDeleted\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\"x\n" +
	"\x13CreateRatingRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1b\n" +
	"\tentity_id\x18\x02 \x01(\tR\bentityId\x12\x16\n" +
	"\x06rating\x18\x03 \x01(\x02R\x06rating\x12\x18\n" +
	"\acomment\x18\x04 \x01(\tR\acomment\":\n" +
	"\x14CreateRatingResponse\x12\"\n" +
	"\x06rating\x18\x01 \x01(\v2\n" +
	".v1.RatingR\x06rating\"\"\n" +
	"\x10GetRatingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"7\n" +
	"\x11GetRatingResponse\x12\"\n" +
	"\x06rating\x18\x01 \x01(\v2\n" +
	".v1.RatingR\x06rating\"\x9f\x01\n" +
	"\x12ListRatingsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1b\n" +
	"\tentity_id\x18\x04 \x01(\tR\bentityId\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x05R\bpageSize\";\n" +
	"\x13ListRatingsResponse\x12$\n" +
	"\aratings\x18\x01 \x03(\v2\n" +
	".v1.RatingR\aratings\"W\n" +
	"\x13UpdateRatingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06rating\x18\x02 \x01(\x02R\x06rating\x12\x18\n" +
	"\acomment\x18\x03 \x01(\tR\acomment\":\n" +
	"\x14UpdateRatingResponse\x12\"\n" +
	"\x06rating\x18\x01 \x01(\v2\n" +
	".v1.RatingR\x06rating\"%\n" +
	"\x13DeleteRatingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"0\n" +
	"\x14DeleteRatingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"Q\n" +
	"\x18CreateRatingReplyRequest\x12\x1b\n" +
	"\trating_id\x18\x01 \x01(\tR\bratingId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"B\n" +
	"\x19CreateRatingReplyResponse\x12%\n" +
	"\x05reply\x18\x01 \x01(\v2\x0f.v1.RatingReplyR\x05reply\"h\n" +
	"\x18ListRatingRepliesRequest\x12\x1b\n" +
	"\trating_id\x18\x01 \x01(\tR\bratingId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"F\n" +
	"\x19ListRatingRepliesResponse\x12)\n" +
	"\areplies\x18\x01 \x03(\v2\x0f.v1.RatingReplyR\areplies\"*\n" +
	"\x18DeleteRatingReplyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"5\n" +
	"\x19DeleteRatingReplyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x19\n" +
	"\x17GetRatingsConfigRequest\"O\n" +
	"\x18GetRatingsConfigResponse\x12\x14\n" +
	"\x05types\x18\x01 \x03(\tR\x05types\x12\x1d\n" +
	"\n" +
	"max_rating\x18\x02 \x01(\x02R\tmaxRatingB\x0fZ\r./helpdesk_v1b\x06proto3"

var (
	file_proto_helpdesk_v1_ratings_proto_rawDescOnce sync.Once
	file_proto_helpdesk_v1_ratings_proto_rawDescData []byte
)

func file_proto_helpdesk_v1_ratings_proto_rawDescGZIP() []byte {
	file_proto_helpdesk_v1_ratings_proto_rawDescOnce.Do(func() {
		file_proto_helpdesk_v1_ratings_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_helpdesk_v1_ratings_proto_rawDesc), len(file_proto_helpdesk_v1_ratings_proto_rawDesc)))
	})
	return file_proto_helpdesk_v1_ratings_proto_rawDescData
}

var file_proto_helpdesk_v1_ratings_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_proto_helpdesk_v1_ratings_proto_goTypes = []any{
	(*Rating)(nil),                    // 0: v1.Rating
	(*RatingReply)(nil),               // 1: v1.RatingReply
	(*CreateRatingRequest)(nil),       // 2: v1.CreateRatingRequest
	(*CreateRatingResponse)(nil),      // 3: v1.CreateRatingResponse
	(*GetRatingRequest)(nil),          // 4: v1.GetRatingRequest
	(*GetRatingResponse)(nil),         // 5: v1.GetRatingResponse
	(*ListRatingsRequest)(nil),        // 6: v1.ListRatingsRequest
	(*ListRatingsResponse)(nil),       // 7: v1.ListRatingsResponse
	(*UpdateRatingRequest)(nil),       // 8: v1.UpdateRatingRequest
	(*UpdateRatingResponse)(nil),      // 9: v1.UpdateRatingResponse
	(*DeleteRatingRequest)(nil),       // 10: v1.DeleteRatingRequest
	(*DeleteRatingResponse)(nil),      // 11: v1.DeleteRatingResponse
	(*CreateRatingReplyRequest)(nil),  // 12: v1.CreateRatingReplyRequest
	(*CreateRatingReplyResponse)(nil), // 13: v1.CreateRatingReplyResponse
	(*ListRatingRepliesRequest)(nil),  // 14: v1.ListRatingRepliesRequest
	(*ListRatingRepliesResponse)(nil), // 15: v1.ListRatingRepliesResponse
	(*DeleteRatingReplyRequest)(nil),  // 16: v1.DeleteRatingReplyRequest
	(*DeleteRatingReplyResponse)(nil), // 17: v1.DeleteRatingReplyResponse
	(*GetRatingsConfigRequest)(nil),   // 18: v1.GetRatingsConfigRequest
	(*GetRatingsConfigResponse)(nil),  // 19: v1.GetRatingsConfigResponse
}
var file_proto_helpdesk_v1_ratings_proto_depIdxs = []int32{
	0, // 0: v1.CreateRatingResponse.rating:type_name -> v1.Rating
	0, // 1: v1.GetRatingResponse.rating:type_name -> v1.Rating
	0, // 2: v1.ListRatingsResponse.ratings:type_name -> v1.Rating
	0, // 3: v1.UpdateRatingResponse.rating:type_name -> v1.Rating
	1, // 4: v1.CreateRatingReplyResponse.reply:type_name -> v1.RatingReply
	1, // 5: v1.ListRatingRepliesResponse.replies:type_name -> v1.RatingReply
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_helpdesk_v1_ratings_proto_init() }
func file_proto_helpdesk_v1_ratings_proto_init() {
	if File_proto_helpdesk_v1_ratings_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_helpdesk_v1_ratings_proto_rawDesc), len(file_proto_helpdesk_v1_ratings_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_helpdesk_v1_ratings_proto_goTypes,
		DependencyIndexes: file_proto_helpdesk_v1_ratings_proto_depIdxs,
		MessageInfos:      file_proto_helpdesk_v1_ratings_proto_msgTypes,
	}.Build()
	File_proto_helpdesk_v1_ratings_proto = out.File
	file_proto_helpdesk_v1_ratings_proto_goTypes = nil
	file_proto_helpdesk_v1_ratings_proto_depIdxs = nil
}
