// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: proto/helpdesk/v1/ratings.proto

package helpdesk_v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Rating with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Rating) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Rating with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in RatingMultiError, or nil if none found.
func (m *Rating) ValidateAll() error {
	return m.validate(true)
}

func (m *Rating) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for UserId

	// no validation rules for Type

	// no validation rules for EntityId

	// no validation rules for Rating

	// no validation rules for Comment

	// no validation rules for CreatedAt

	// no validation rules for UpdatedAt

	if len(errors) > 0 {
		return RatingMultiError(errors)
	}

	return nil
}

// RatingMultiError is an error wrapping multiple validation errors returned by
// Rating.ValidateAll() if the designated constraints aren't met.
type RatingMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RatingMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RatingMultiError) AllErrors() []error { return m }

// RatingValidationError is the validation error returned by Rating.Validate if
// the designated constraints aren't met.
type RatingValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RatingValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RatingValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RatingValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RatingValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RatingValidationError) ErrorName() string { return "RatingValidationError" }

// Error satisfies the builtin error interface
func (e RatingValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRating.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RatingValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RatingValidationError{}

// Validate checks the field values on RatingReply with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *RatingReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RatingReply with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in RatingReplyMultiError, or
// nil if none found.
func (m *RatingReply) ValidateAll() error {
	return m.validate(true)
}

func (m *RatingReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for RatingId

	// no validation rules for UserId

	// no validation rules for Role

	// no validation rules for Message

	// no validation rules for IsDeleted

	// no validation rules for CreatedAt

	if len(errors) > 0 {
		return RatingReplyMultiError(errors)
	}

	return nil
}

// RatingReplyMultiError is an error wrapping multiple validation errors
// returned by RatingReply.ValidateAll() if the designated constraints aren't met.
type RatingReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RatingReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RatingReplyMultiError) AllErrors() []error { return m }

// RatingReplyValidationError is the validation error returned by
// RatingReply.Validate if the designated constraints aren't met.
type RatingReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RatingReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RatingReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RatingReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RatingReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RatingReplyValidationError) ErrorName() string { return "RatingReplyValidationError" }

// Error satisfies the builtin error interface
func (e RatingReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRatingReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RatingReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RatingReplyValidationError{}

// Validate checks the field values on CreateRatingRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateRatingRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateRatingRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateRatingRequestMultiError, or nil if none found.
func (m *CreateRatingRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateRatingRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Type

	// no validation rules for EntityId

	// no validation rules for Rating

	// no validation rules for Comment

	if len(errors) > 0 {
		return CreateRatingRequestMultiError(errors)
	}

	return nil
}

// CreateRatingRequestMultiError is an error wrapping multiple validation
// errors returned by CreateRatingRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateRatingRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateRatingRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateRatingRequestMultiError) AllErrors() []error { return m }

// CreateRatingRequestValidationError is the validation error returned by
// CreateRatingRequest.Validate if the designated constraints aren't met.
type CreateRatingRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateRatingRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateRatingRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateRatingRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateRatingRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateRatingRequestValidationError) ErrorName() string {
	return "CreateRatingRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateRatingRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateRatingRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateRatingRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateRatingRequestValidationError{}

// Validate checks the field values on CreateRatingResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateRatingResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateRatingResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateRatingResponseMultiError, or nil if none found.
func (m *CreateRatingResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateRatingResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetRating()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateRatingResponseValidationError{
					field:  "Rating",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateRatingResponseValidationError{
					field:  "Rating",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRating()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateRatingResponseValidationError{
				field:  "Rating",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateRatingResponseMultiError(errors)
	}

	return nil
}

// CreateRatingResponseMultiError is an error wrapping multiple validation
// errors returned by CreateRatingResponse.ValidateAll() if the designated
// constraints aren't met.
type CreateRatingResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateRatingResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateRatingResponseMultiError) AllErrors() []error { return m }

// CreateRatingResponseValidationError is the validation error returned by
// CreateRatingResponse.Validate if the designated constraints aren't met.
type CreateRatingResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateRatingResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateRatingResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateRatingResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateRatingResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateRatingResponseValidationError) ErrorName() string {
	return "CreateRatingResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateRatingResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateRatingResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateRatingResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateRatingResponseValidationError{}

// Validate checks the field values on GetRatingRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetRatingRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetRatingRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetRatingRequestMultiError, or nil if none found.
func (m *GetRatingRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetRatingRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return GetRatingRequestMultiError(errors)
	}

	return nil
}

// GetRatingRequestMultiError is an error wrapping multiple validation errors
// returned by GetRatingRequest.ValidateAll() if the designated constraints
// aren't met.
type GetRatingRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetRatingRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetRatingRequestMultiError) AllErrors() []error { return m }

// GetRatingRequestValidationError is the validation error returned by
// GetRatingRequest.Validate if the designated constraints aren't met.
type GetRatingRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetRatingRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetRatingRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetRatingRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetRatingRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetRatingRequestValidationError) ErrorName() string { return "GetRatingRequestValidationError" }

// Error satisfies the builtin error interface
func (e GetRatingRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetRatingRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetRatingRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetRatingRequestValidationError{}

// Validate checks the field values on GetRatingResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetRatingResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetRatingResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetRatingResponseMultiError, or nil if none found.
func (m *GetRatingResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetRatingResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetRating()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetRatingResponseValidationError{
					field:  "Rating",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetRatingResponseValidationError{
					field:  "Rating",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRating()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetRatingResponseValidationError{
				field:  "Rating",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetRatingResponseMultiError(errors)
	}

	return nil
}

// GetRatingResponseMultiError is an error wrapping multiple validation errors
// returned by GetRatingResponse.ValidateAll() if the designated constraints
// aren't met.
type GetRatingResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetRatingResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetRatingResponseMultiError) AllErrors() []error { return m }

// GetRatingResponseValidationError is the validation error returned by
// GetRatingResponse.Validate if the designated constraints aren't met.
type GetRatingResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetRatingResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetRatingResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetRatingResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetRatingResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetRatingResponseValidationError) ErrorName() string {
	return "GetRatingResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetRatingResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetRatingResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetRatingResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetRatingResponseValidationError{}

// Validate checks the field values on ListRatingsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListRatingsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListRatingsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListRatingsRequestMultiError, or nil if none found.
func (m *ListRatingsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListRatingsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for UserId

	// no validation rules for Type

	// no validation rules for EntityId

	// no validation rules for Page

	// no validation rules for PageSize

	if len(errors) > 0 {
		return ListRatingsRequestMultiError(errors)
	}

	return nil
}

// ListRatingsRequestMultiError is an error wrapping multiple validation errors
// returned by ListRatingsRequest.ValidateAll() if the designated constraints
// aren't met.
type ListRatingsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListRatingsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListRatingsRequestMultiError) AllErrors() []error { return m }

// ListRatingsRequestValidationError is the validation error returned by
// ListRatingsRequest.Validate if the designated constraints aren't met.
type ListRatingsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListRatingsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListRatingsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListRatingsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListRatingsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListRatingsRequestValidationError) ErrorName() string {
	return "ListRatingsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListRatingsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListRatingsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListRatingsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListRatingsRequestValidationError{}

// Validate checks the field values on ListRatingsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListRatingsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListRatingsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListRatingsResponseMultiError, or nil if none found.
func (m *ListRatingsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListRatingsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetRatings() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListRatingsResponseValidationError{
						field:  fmt.Sprintf("Ratings[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListRatingsResponseValidationError{
						field:  fmt.Sprintf("Ratings[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListRatingsResponseValidationError{
					field:  fmt.Sprintf("Ratings[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListRatingsResponseMultiError(errors)
	}

	return nil
}

// ListRatingsResponseMultiError is an error wrapping multiple validation
// errors returned by ListRatingsResponse.ValidateAll() if the designated
// constraints aren't met.
type ListRatingsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListRatingsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListRatingsResponseMultiError) AllErrors() []error { return m }

// ListRatingsResponseValidationError is the validation error returned by
// ListRatingsResponse.Validate if the designated constraints aren't met.
type ListRatingsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListRatingsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListRatingsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListRatingsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListRatingsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListRatingsResponseValidationError) ErrorName() string {
	return "ListRatingsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListRatingsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListRatingsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListRatingsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListRatingsResponseValidationError{}

// Validate checks the field values on UpdateRatingRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateRatingRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateRatingRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateRatingRequestMultiError, or nil if none found.
func (m *UpdateRatingRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateRatingRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Rating

	// no validation rules for Comment

	if len(errors) > 0 {
		return UpdateRatingRequestMultiError(errors)
	}

	return nil
}

// UpdateRatingRequestMultiError is an error wrapping multiple validation
// errors returned by UpdateRatingRequest.ValidateAll() if the designated
// constraints aren't met.
type UpdateRatingRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateRatingRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateRatingRequestMultiError) AllErrors() []error { return m }

// UpdateRatingRequestValidationError is the validation error returned by
// UpdateRatingRequest.Validate if the designated constraints aren't met.
type UpdateRatingRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateRatingRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateRatingRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateRatingRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateRatingRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateRatingRequestValidationError) ErrorName() string {
	return "UpdateRatingRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateRatingRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateRatingRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateRatingRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateRatingRequestValidationError{}

// Validate checks the field values on UpdateRatingResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateRatingResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateRatingResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateRatingResponseMultiError, or nil if none found.
func (m *UpdateRatingResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateRatingResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetRating()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateRatingResponseValidationError{
					field:  "Rating",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateRatingResponseValidationError{
					field:  "Rating",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRating()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateRatingResponseValidationError{
				field:  "Rating",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UpdateRatingResponseMultiError(errors)
	}

	return nil
}

// UpdateRatingResponseMultiError is an error wrapping multiple validation
// errors returned by UpdateRatingResponse.ValidateAll() if the designated
// constraints aren't met.
type UpdateRatingResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateRatingResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateRatingResponseMultiError) AllErrors() []error { return m }

// UpdateRatingResponseValidationError is the validation error returned by
// UpdateRatingResponse.Validate if the designated constraints aren't met.
type UpdateRatingResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateRatingResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateRatingResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateRatingResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateRatingResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateRatingResponseValidationError) ErrorName() string {
	return "UpdateRatingResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateRatingResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateRatingResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateRatingResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateRatingResponseValidationError{}

// Validate checks the field values on DeleteRatingRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteRatingRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteRatingRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteRatingRequestMultiError, or nil if none found.
func (m *DeleteRatingRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteRatingRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return DeleteRatingRequestMultiError(errors)
	}

	return nil
}

// DeleteRatingRequestMultiError is an error wrapping multiple validation
// errors returned by DeleteRatingRequest.ValidateAll() if the designated
// constraints aren't met.
type DeleteRatingRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteRatingRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteRatingRequestMultiError) AllErrors() []error { return m }

// DeleteRatingRequestValidationError is the validation error returned by
// DeleteRatingRequest.Validate if the designated constraints aren't met.
type DeleteRatingRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteRatingRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteRatingRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteRatingRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteRatingRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteRatingRequestValidationError) ErrorName() string {
	return "DeleteRatingRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteRatingRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteRatingRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteRatingRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteRatingRequestValidationError{}

// Validate checks the field values on DeleteRatingResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteRatingResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteRatingResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteRatingResponseMultiError, or nil if none found.
func (m *DeleteRatingResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteRatingResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Success

	if len(errors) > 0 {
		return DeleteRatingResponseMultiError(errors)
	}

	return nil
}

// DeleteRatingResponseMultiError is an error wrapping multiple validation
// errors returned by DeleteRatingResponse.ValidateAll() if the designated
// constraints aren't met.
type DeleteRatingResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteRatingResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteRatingResponseMultiError) AllErrors() []error { return m }

// DeleteRatingResponseValidationError is the validation error returned by
// DeleteRatingResponse.Validate if the designated constraints aren't met.
type DeleteRatingResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteRatingResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteRatingResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteRatingResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteRatingResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteRatingResponseValidationError) ErrorName() string {
	return "DeleteRatingResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteRatingResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteRatingResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteRatingResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteRatingResponseValidationError{}

// Validate checks the field values on CreateRatingReplyRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateRatingReplyRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateRatingReplyRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateRatingReplyRequestMultiError, or nil if none found.
func (m *CreateRatingReplyRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateRatingReplyRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for RatingId

	// no validation rules for Message

	if len(errors) > 0 {
		return CreateRatingReplyRequestMultiError(errors)
	}

	return nil
}

// CreateRatingReplyRequestMultiError is an error wrapping multiple validation
// errors returned by CreateRatingReplyRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateRatingReplyRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateRatingReplyRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateRatingReplyRequestMultiError) AllErrors() []error { return m }

// CreateRatingReplyRequestValidationError is the validation error returned by
// CreateRatingReplyRequest.Validate if the designated constraints aren't met.
type CreateRatingReplyRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateRatingReplyRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateRatingReplyRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateRatingReplyRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateRatingReplyRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateRatingReplyRequestValidationError) ErrorName() string {
	return "CreateRatingReplyRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateRatingReplyRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateRatingReplyRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateRatingReplyRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateRatingReplyRequestValidationError{}

// Validate checks the field values on CreateRatingReplyResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateRatingReplyResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateRatingReplyResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateRatingReplyResponseMultiError, or nil if none found.
func (m *CreateRatingReplyResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateRatingReplyResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetReply()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateRatingReplyResponseValidationError{
					field:  "Reply",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateRatingReplyResponseValidationError{
					field:  "Reply",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetReply()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateRatingReplyResponseValidationError{
				field:  "Reply",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateRatingReplyResponseMultiError(errors)
	}

	return nil
}

// CreateRatingReplyResponseMultiError is an error wrapping multiple validation
// errors returned by CreateRatingReplyResponse.ValidateAll() if the
// designated constraints aren't met.
type CreateRatingReplyResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateRatingReplyResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateRatingReplyResponseMultiError) AllErrors() []error { return m }

// CreateRatingReplyResponseValidationError is the validation error returned by
// CreateRatingReplyResponse.Validate if the designated constraints aren't met.
type CreateRatingReplyResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateRatingReplyResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateRatingReplyResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateRatingReplyResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateRatingReplyResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateRatingReplyResponseValidationError) ErrorName() string {
	return "CreateRatingReplyResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateRatingReplyResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateRatingReplyResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateRatingReplyResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateRatingReplyResponseValidationError{}

// Validate checks the field values on ListRatingRepliesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListRatingRepliesRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListRatingRepliesRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListRatingRepliesRequestMultiError, or nil if none found.
func (m *ListRatingRepliesRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListRatingRepliesRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for RatingId

	// no validation rules for Page

	// no validation rules for PageSize

	if len(errors) > 0 {
		return ListRatingRepliesRequestMultiError(errors)
	}

	return nil
}

// ListRatingRepliesRequestMultiError is an error wrapping multiple validation
// errors returned by ListRatingRepliesRequest.ValidateAll() if the designated
// constraints aren't met.
type ListRatingRepliesRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListRatingRepliesRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListRatingRepliesRequestMultiError) AllErrors() []error { return m }

// ListRatingRepliesRequestValidationError is the validation error returned by
// ListRatingRepliesRequest.Validate if the designated constraints aren't met.
type ListRatingRepliesRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListRatingRepliesRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListRatingRepliesRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListRatingRepliesRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListRatingRepliesRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListRatingRepliesRequestValidationError) ErrorName() string {
	return "ListRatingRepliesRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListRatingRepliesRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListRatingRepliesRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListRatingRepliesRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListRatingRepliesRequestValidationError{}

// Validate checks the field values on ListRatingRepliesResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListRatingRepliesResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListRatingRepliesResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListRatingRepliesResponseMultiError, or nil if none found.
func (m *ListRatingRepliesResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListRatingRepliesResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetReplies() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListRatingRepliesResponseValidationError{
						field:  fmt.Sprintf("Replies[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListRatingRepliesResponseValidationError{
						field:  fmt.Sprintf("Replies[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListRatingRepliesResponseValidationError{
					field:  fmt.Sprintf("Replies[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListRatingRepliesResponseMultiError(errors)
	}

	return nil
}

// ListRatingRepliesResponseMultiError is an error wrapping multiple validation
// errors returned by ListRatingRepliesResponse.ValidateAll() if the
// designated constraints aren't met.
type ListRatingRepliesResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListRatingRepliesResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListRatingRepliesResponseMultiError) AllErrors() []error { return m }

// ListRatingRepliesResponseValidationError is the validation error returned by
// ListRatingRepliesResponse.Validate if the designated constraints aren't met.
type ListRatingRepliesResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListRatingRepliesResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListRatingRepliesResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListRatingRepliesResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListRatingRepliesResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListRatingRepliesResponseValidationError) ErrorName() string {
	return "ListRatingRepliesResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListRatingRepliesResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListRatingRepliesResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListRatingRepliesResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListRatingRepliesResponseValidationError{}

// Validate checks the field values on DeleteRatingReplyRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteRatingReplyRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteRatingReplyRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteRatingReplyRequestMultiError, or nil if none found.
func (m *DeleteRatingReplyRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteRatingReplyRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return DeleteRatingReplyRequestMultiError(errors)
	}

	return nil
}

// DeleteRatingReplyRequestMultiError is an error wrapping multiple validation
// errors returned by DeleteRatingReplyRequest.ValidateAll() if the designated
// constraints aren't met.
type DeleteRatingReplyRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteRatingReplyRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteRatingReplyRequestMultiError) AllErrors() []error { return m }

// DeleteRatingReplyRequestValidationError is the validation error returned by
// DeleteRatingReplyRequest.Validate if the designated constraints aren't met.
type DeleteRatingReplyRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteRatingReplyRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteRatingReplyRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteRatingReplyRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteRatingReplyRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteRatingReplyRequestValidationError) ErrorName() string {
	return "DeleteRatingReplyRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteRatingReplyRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteRatingReplyRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteRatingReplyRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteRatingReplyRequestValidationError{}

// Validate checks the field values on DeleteRatingReplyResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteRatingReplyResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteRatingReplyResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteRatingReplyResponseMultiError, or nil if none found.
func (m *DeleteRatingReplyResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteRatingReplyResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Success

	if len(errors) > 0 {
		return DeleteRatingReplyResponseMultiError(errors)
	}

	return nil
}

// DeleteRatingReplyResponseMultiError is an error wrapping multiple validation
// errors returned by DeleteRatingReplyResponse.ValidateAll() if the
// designated constraints aren't met.
type DeleteRatingReplyResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteRatingReplyResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteRatingReplyResponseMultiError) AllErrors() []error { return m }

// DeleteRatingReplyResponseValidationError is the validation error returned by
// DeleteRatingReplyResponse.Validate if the designated constraints aren't met.
type DeleteRatingReplyResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteRatingReplyResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteRatingReplyResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteRatingReplyResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteRatingReplyResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteRatingReplyResponseValidationError) ErrorName() string {
	return "DeleteRatingReplyResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteRatingReplyResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteRatingReplyResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteRatingReplyResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteRatingReplyResponseValidationError{}

// Validate checks the field values on GetRatingsConfigRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetRatingsConfigRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetRatingsConfigRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetRatingsConfigRequestMultiError, or nil if none found.
func (m *GetRatingsConfigRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetRatingsConfigRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GetRatingsConfigRequestMultiError(errors)
	}

	return nil
}

// GetRatingsConfigRequestMultiError is an error wrapping multiple validation
// errors returned by GetRatingsConfigRequest.ValidateAll() if the designated
// constraints aren't met.
type GetRatingsConfigRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetRatingsConfigRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetRatingsConfigRequestMultiError) AllErrors() []error { return m }

// GetRatingsConfigRequestValidationError is the validation error returned by
// GetRatingsConfigRequest.Validate if the designated constraints aren't met.
type GetRatingsConfigRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetRatingsConfigRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetRatingsConfigRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetRatingsConfigRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetRatingsConfigRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetRatingsConfigRequestValidationError) ErrorName() string {
	return "GetRatingsConfigRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetRatingsConfigRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetRatingsConfigRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetRatingsConfigRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetRatingsConfigRequestValidationError{}

// Validate checks the field values on GetRatingsConfigResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetRatingsConfigResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetRatingsConfigResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetRatingsConfigResponseMultiError, or nil if none found.
func (m *GetRatingsConfigResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetRatingsConfigResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for MaxRating

	if len(errors) > 0 {
		return GetRatingsConfigResponseMultiError(errors)
	}

	return nil
}

// GetRatingsConfigResponseMultiError is an error wrapping multiple validation
// errors returned by GetRatingsConfigResponse.ValidateAll() if the designated
// constraints aren't met.
type GetRatingsConfigResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetRatingsConfigResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetRatingsConfigResponseMultiError) AllErrors() []error { return m }

// GetRatingsConfigResponseValidationError is the validation error returned by
// GetRatingsConfigResponse.Validate if the designated constraints aren't met.
type GetRatingsConfigResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetRatingsConfigResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetRatingsConfigResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetRatingsConfigResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetRatingsConfigResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetRatingsConfigResponseValidationError) ErrorName() string {
	return "GetRatingsConfigResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetRatingsConfigResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetRatingsConfigResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetRatingsConfigResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetRatingsConfigResponseValidationError{}
